export const PERMISSIONS = {
  "tenants.view": "View tenants",
  "tenants.view_details": "View tenant details",
  "tenants.create": "Create tenants",
  "tenants.edit": "Edit tenants",
  "tenants.suspend": "Suspend tenants",
  "tenants.unsuspend": "Unsuspend tenants",
  "tenants.delete": "Delete tenants",
  "tenants.impersonate": "Impersonate tenant users",
  "tenants.export": "Export tenant data",
  "tenants.view_finance": "View tenant finance",
  "tenants.manage_finance": "Manage tenant finance",
  "tenants.manage_subscription": "Manage subscriptions",
  "tenants.manage_modules": "Manage tenant modules",
  "tenants.manage_users": "Manage tenant users",
  "tenants.manage_settings": "Manage tenant settings",
  "tenants.manage_pilot_grants": "Manage pilot grants",
  "tenants.grant_permanent_free": "Grant permanent free access",
  "tenants.set_custom_pricing": "Set custom pricing",
  "tenants.gdpr_export": "Run GDPR export",
  "platform_users.view": "View platform users",
  "platform_users.invite": "Invite platform users",
  "platform_users.edit_role": "Edit platform user roles",
  "platform_users.edit_permissions": "Edit platform user permissions",
  "platform_users.suspend": "Suspend platform users",
  "platform_users.delete": "Delete platform users",
  "platform_users.view_activity": "View platform user activity",
  "marketplace.view": "View marketplace",
  "marketplace.review_modules": "Review marketplace modules",
  "marketplace.suspend_module": "Suspend modules",
  "marketplace.ban_module": "Ban modules",
  "marketplace.feature_module": "Feature modules",
  "marketplace.override_price": "Override module pricing",
  "marketplace.manage_flags": "Manage marketplace flags",
  "marketplace.manage_reviews": "Manage marketplace reviews",
  "marketplace.manage_pilot_grants": "Manage marketplace pilot grants",
  "marketplace.bulk_pilot_grants": "Bulk-create pilot grants",
  "marketplace.manage_pricing": "Manage marketplace pricing",
  "publishers.view": "View publishers",
  "publishers.approve": "Approve publishers",
  "publishers.reject": "Reject publishers",
  "publishers.suspend": "Suspend publishers",
  "publishers.ban": "Ban publishers",
  "publishers.manage_revenue_share": "Manage publisher revenue share",
  "publishers.manage_tier": "Manage publisher tier",
  "publishers.process_payouts": "Process publisher payouts",
  "publishers.view_payouts": "View publisher payouts",
  "billing.view_dashboard": "View billing dashboard",
  "billing.view_invoices": "View invoices",
  "billing.manage_invoices": "Manage invoices",
  "billing.view_subscriptions": "View subscriptions",
  "billing.manage_subscriptions": "Manage subscriptions",
  "billing.view_reports": "View billing reports",
  "billing.export_reports": "Export billing reports",
  "billing.manage_plans": "Manage plans",
  "billing.view_publisher_payouts": "View publisher payouts",
  "billing.process_payouts": "Process payouts",
  "crm.view_own": "View own CRM leads",
  "crm.view_shared": "View shared CRM leads",
  "crm.view_all": "View all CRM leads",
  "crm.create_lead": "Create CRM leads",
  "crm.edit_own_lead": "Edit own CRM leads",
  "crm.edit_any_lead": "Edit any CRM lead",
  "crm.delete_own_lead": "Delete own CRM leads",
  "crm.delete_any_lead": "Delete any CRM lead",
  "crm.assign_lead": "Assign CRM leads",
  "crm.share_lead": "Share CRM leads",
  "crm.create_proposal": "Create CRM proposals",
  "crm.convert_to_tenant": "Convert leads to tenants",
  "crm.manage_pipeline": "Manage CRM pipeline settings",
  "crm.view_reports": "View CRM reports",
  "communications.view": "View communications",
  "communications.send_broadcast": "Send broadcasts",
  "communications.send_sms": "Send SMS broadcasts",
  "communications.manage_templates": "Manage templates",
  "communications.view_logs": "View delivery logs",
  "communications.manage_announcements": "Manage announcements",
  "knowledge_base.view": "View knowledge base",
  "knowledge_base.create": "Create knowledge base articles",
  "knowledge_base.edit": "Edit knowledge base articles",
  "knowledge_base.publish": "Publish knowledge base articles",
  "knowledge_base.delete": "Delete knowledge base articles",
  "analytics.view_platform": "View platform analytics",
  "analytics.view_business": "View business analytics",
  "analytics.export": "Export analytics",
  "analytics.manage_reports": "Manage analytics reports",
  "security.view_dashboard": "View security dashboard",
  "security.view_audit_log": "View security audit log",
  "security.export_audit_log": "Export security audit log",
  "security.manage_api_keys": "Manage API keys",
  "security.manage_webhooks": "Manage webhooks",
  "security.flag_audit_entries": "Flag audit entries",
  "settings.view": "View settings",
  "settings.edit_general": "Edit general settings",
  "settings.edit_email": "Edit email settings",
  "settings.edit_sms": "Edit SMS settings",
  "settings.edit_payments": "Edit payment settings",
  "settings.edit_security": "Edit security settings",
  "settings.edit_integrations": "Edit integrations",
  "settings.maintenance_mode": "Toggle maintenance mode",
  "settings.manage_feature_flags": "Manage feature flags",
  "settings.manage_sla": "Manage SLA",
  "support.view": "View support tickets",
  "support.assign": "Assign support tickets",
  "support.reply": "Reply to support tickets",
  "support.close": "Close support tickets",
  "support.escalate": "Escalate support tickets",
  "support.view_internal_notes": "View internal notes",
  "waitlist.view": "View waitlist",
  "waitlist.create": "Create waitlist entries",
  "waitlist.edit": "Edit waitlist entries",
  "waitlist.delete": "Delete waitlist entries",
  "waitlist.invite": "Invite waitlist leads",
  "waitlist.reject": "Reject waitlist leads",
  "onboarding.view": "View onboarding",
  "onboarding.manage": "Manage onboarding",
  "resellers.view": "View resellers",
  "resellers.approve": "Approve resellers",
  "resellers.reject": "Reject resellers",
  "resellers.manage_tier": "Manage reseller tier",
  "resellers.manage_commission": "Manage reseller commission",
  "resellers.suspend": "Suspend resellers",
  "resellers.terminate": "Terminate resellers",
  "resellers.process_payouts": "Process reseller payouts",
  "resellers.manage_materials": "Manage reseller materials",
  "resellers.manage_directory": "Manage reseller directory",
  "resellers.manage_tiers_config": "Manage reseller tiers configuration",
  "staff_performance.view": "View all staff performance",
  "staff_performance.view_own": "View own staff performance",
  "staff_performance.add_notes": "Add performance notes",
  "pm.view_own": "View own PM projects",
  "pm.view_shared": "View shared PM projects",
  "pm.view_all": "View all PM projects",
  "pm.create_workspace": "Create PM workspaces",
  "pm.manage_workspace": "Manage PM workspaces",
  "pm.create_project": "Create PM projects",
  "pm.edit_own_project": "Edit own PM projects",
  "pm.edit_any_project": "Edit any PM project",
  "pm.delete_own_project": "Delete own PM projects",
  "pm.delete_any_project": "Delete any PM project",
  "pm.manage_members": "Manage PM project members",
  "pm.create_task": "Create PM tasks",
  "pm.edit_own_task": "Edit own PM tasks",
  "pm.edit_any_task": "Edit any PM tasks",
  "pm.delete_any_task": "Delete any PM task",
  "pm.manage_sprints": "Manage PM sprints",
  "pm.log_time": "Log task time",
  "pm.view_time_logs": "View task time logs",
} as const;

export const ALL_PERMISSION_KEYS = Object.keys(PERMISSIONS);

export const SYSTEM_ROLE_PERMISSIONS: Record<string, string[]> = {
  master_admin: ["*"],
  super_admin: ALL_PERMISSION_KEYS,
  platform_manager: [
    "tenants.view",
    "tenants.view_details",
    "tenants.create",
    "tenants.edit",
    "tenants.suspend",
    "tenants.unsuspend",
    "tenants.export",
    "tenants.manage_subscription",
    "tenants.manage_modules",
    "tenants.manage_users",
    "tenants.manage_pilot_grants",
    "platform_users.view",
    "waitlist.view",
    "waitlist.create",
    "waitlist.edit",
    "waitlist.invite",
    "waitlist.reject",
    "onboarding.view",
    "onboarding.manage",
    "crm.view_own",
    "crm.view_shared",
    "crm.create_lead",
    "crm.edit_own_lead",
    "crm.assign_lead",
    "crm.share_lead",
    "crm.create_proposal",
    "crm.convert_to_tenant",
    "pm.view_own",
    "pm.view_shared",
    "pm.create_workspace",
    "pm.manage_workspace",
    "pm.create_project",
    "pm.edit_own_project",
    "pm.manage_members",
    "pm.create_task",
    "pm.edit_own_task",
    "pm.manage_sprints",
    "pm.log_time",
    "pm.view_time_logs",
    "communications.view",
    "communications.send_broadcast",
    "communications.manage_announcements",
    "marketplace.view",
    "marketplace.feature_module",
    "marketplace.manage_pilot_grants",
    "analytics.view_platform",
  ],
  support_agent: [
    "tenants.view",
    "tenants.view_details",
    "tenants.manage_users",
    "support.view",
    "support.assign",
    "support.reply",
    "support.close",
    "support.view_internal_notes",
    "crm.view_own",
    "crm.view_shared",
    "communications.view",
    "knowledge_base.view",
    "knowledge_base.create",
    "knowledge_base.edit",
    "onboarding.view",
    "pm.view_own",
    "pm.view_shared",
  ],
  billing_admin: [
    "tenants.view",
    "tenants.view_details",
    "tenants.view_finance",
    "tenants.manage_finance",
    "tenants.manage_subscription",
    "tenants.set_custom_pricing",
    "billing.view_dashboard",
    "billing.view_invoices",
    "billing.manage_invoices",
    "billing.view_subscriptions",
    "billing.manage_subscriptions",
    "billing.view_reports",
    "billing.export_reports",
    "billing.manage_plans",
    "billing.view_publisher_payouts",
    "billing.process_payouts",
  ],
  marketplace_reviewer: [
    "marketplace.view",
    "marketplace.review_modules",
    "marketplace.suspend_module",
    "marketplace.feature_module",
    "marketplace.manage_flags",
    "marketplace.manage_reviews",
    "marketplace.manage_pilot_grants",
    "marketplace.manage_pricing",
    "publishers.view",
    "publishers.approve",
    "publishers.reject",
    "publishers.suspend",
  ],
  content_moderator: [
    "communications.view",
    "communications.manage_templates",
    "communications.manage_announcements",
    "knowledge_base.view",
    "knowledge_base.create",
    "knowledge_base.edit",
    "knowledge_base.publish",
    "knowledge_base.delete",
    "marketplace.view",
    "marketplace.manage_reviews",
  ],
  analytics_viewer: [
    "analytics.view_platform",
    "analytics.view_business",
    "analytics.export",
    "billing.view_dashboard",
    "billing.view_reports",
    "crm.view_own",
    "pm.view_own",
    "support.view",
  ],
};
