/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as actions_ai_index from "../actions/ai/index.js";
import type * as actions_ai_support from "../actions/ai/support.js";
import type * as actions_auth_password from "../actions/auth/password.js";
import type * as actions_auth_twoFactor from "../actions/auth/twoFactor.js";
import type * as actions_communications_email from "../actions/communications/email.js";
import type * as actions_communications_push from "../actions/communications/push.js";
import type * as actions_communications_sms from "../actions/communications/sms.js";
import type * as actions_payments_airtel from "../actions/payments/airtel.js";
import type * as actions_payments_bankTransfer from "../actions/payments/bankTransfer.js";
import type * as actions_payments_mpesa from "../actions/payments/mpesa.js";
import type * as actions_payments_stripe from "../actions/payments/stripe.js";
import type * as auth from "../auth.js";
import type * as crons from "../crons.js";
import type * as dev_seed from "../dev/seed.js";
import type * as helpers_auditLog from "../helpers/auditLog.js";
import type * as helpers_authorize from "../helpers/authorize.js";
import type * as helpers_idGenerator from "../helpers/idGenerator.js";
import type * as helpers_moduleGuard from "../helpers/moduleGuard.js";
import type * as helpers_phoneUtils from "../helpers/phoneUtils.js";
import type * as helpers_platformGuard from "../helpers/platformGuard.js";
import type * as helpers_publisherGuard from "../helpers/publisherGuard.js";
import type * as helpers_tenantGuard from "../helpers/tenantGuard.js";
import type * as http from "../http.js";
import type * as index from "../index.js";
import type * as modules_academics_assignments from "../modules/academics/assignments.js";
import type * as modules_academics_index from "../modules/academics/index.js";
import type * as modules_academics_mutations from "../modules/academics/mutations.js";
import type * as modules_academics_queries from "../modules/academics/queries.js";
import type * as modules_admissions_index from "../modules/admissions/index.js";
import type * as modules_admissions_mutations from "../modules/admissions/mutations.js";
import type * as modules_admissions_queries from "../modules/admissions/queries.js";
import type * as modules_auth_loginAttempts from "../modules/auth/loginAttempts.js";
import type * as modules_auth_passwordHelpers from "../modules/auth/passwordHelpers.js";
import type * as modules_auth_passwordPolicy from "../modules/auth/passwordPolicy.js";
import type * as modules_auth_twoFactorHelpers from "../modules/auth/twoFactorHelpers.js";
import type * as modules_communications_email from "../modules/communications/email.js";
import type * as modules_communications_emailTemplates from "../modules/communications/emailTemplates.js";
import type * as modules_communications_index from "../modules/communications/index.js";
import type * as modules_communications_mutations from "../modules/communications/mutations.js";
import type * as modules_communications_platform from "../modules/communications/platform.js";
import type * as modules_communications_platformInviteEmails from "../modules/communications/platformInviteEmails.js";
import type * as modules_communications_queries from "../modules/communications/queries.js";
import type * as modules_communications_sms from "../modules/communications/sms.js";
import type * as modules_communications_templates from "../modules/communications/templates.js";
import type * as modules_communications_workos from "../modules/communications/workos.js";
import type * as modules_ecommerce_index from "../modules/ecommerce/index.js";
import type * as modules_ecommerce_mutations from "../modules/ecommerce/mutations.js";
import type * as modules_ecommerce_queries from "../modules/ecommerce/queries.js";
import type * as modules_ewallet_index from "../modules/ewallet/index.js";
import type * as modules_ewallet_mutations from "../modules/ewallet/mutations.js";
import type * as modules_ewallet_queries from "../modules/ewallet/queries.js";
import type * as modules_finance_actions from "../modules/finance/actions.js";
import type * as modules_finance_index from "../modules/finance/index.js";
import type * as modules_finance_mutations from "../modules/finance/mutations.js";
import type * as modules_finance_paymentUtils from "../modules/finance/paymentUtils.js";
import type * as modules_finance_queries from "../modules/finance/queries.js";
import type * as modules_hr_index from "../modules/hr/index.js";
import type * as modules_hr_mutations from "../modules/hr/mutations.js";
import type * as modules_hr_queries from "../modules/hr/queries.js";
import type * as modules_library_index from "../modules/library/index.js";
import type * as modules_library_mutations from "../modules/library/mutations.js";
import type * as modules_library_queries from "../modules/library/queries.js";
import type * as modules_marketplace_analytics from "../modules/marketplace/analytics.js";
import type * as modules_marketplace_flags from "../modules/marketplace/flags.js";
import type * as modules_marketplace_moduleDefinitions from "../modules/marketplace/moduleDefinitions.js";
import type * as modules_marketplace_modules from "../modules/marketplace/modules.js";
import type * as modules_marketplace_mutations from "../modules/marketplace/mutations.js";
import type * as modules_marketplace_platform from "../modules/marketplace/platform.js";
import type * as modules_marketplace_publisherOps from "../modules/marketplace/publisherOps.js";
import type * as modules_marketplace_publishers from "../modules/marketplace/publishers.js";
import type * as modules_marketplace_queries from "../modules/marketplace/queries.js";
import type * as modules_marketplace_reviews from "../modules/marketplace/reviews.js";
import type * as modules_marketplace_seed from "../modules/marketplace/seed.js";
import type * as modules_marketplace_tierModules from "../modules/marketplace/tierModules.js";
import type * as modules_notes_index from "../modules/notes/index.js";
import type * as modules_notes_mutations from "../modules/notes/mutations.js";
import type * as modules_notes_queries from "../modules/notes/queries.js";
import type * as modules_platform_announcements from "../modules/platform/announcements.js";
import type * as modules_platform_crm from "../modules/platform/crm.js";
import type * as modules_platform_currency from "../modules/platform/currency.js";
import type * as modules_platform_onboarding from "../modules/platform/onboarding.js";
import type * as modules_platform_ops from "../modules/platform/ops.js";
import type * as modules_platform_pilotGrants from "../modules/platform/pilotGrants.js";
import type * as modules_platform_rbac from "../modules/platform/rbac.js";
import type * as modules_platform_subscriptions from "../modules/platform/subscriptions.js";
import type * as modules_platform_support from "../modules/platform/support.js";
import type * as modules_platform_users from "../modules/platform/users.js";
import type * as modules_platform_waitlist from "../modules/platform/waitlist.js";
import type * as modules_pm_deploys from "../modules/pm/deploys.js";
import type * as modules_pm_epics from "../modules/pm/epics.js";
import type * as modules_pm_github from "../modules/pm/github.js";
import type * as modules_pm_index from "../modules/pm/index.js";
import type * as modules_pm_projects from "../modules/pm/projects.js";
import type * as modules_pm_roles from "../modules/pm/roles.js";
import type * as modules_pm_tasks from "../modules/pm/tasks.js";
import type * as modules_pm_timeLogs from "../modules/pm/timeLogs.js";
import type * as modules_pm_workspaces from "../modules/pm/workspaces.js";
import type * as modules_portal_alumni_mutations from "../modules/portal/alumni/mutations.js";
import type * as modules_portal_alumni_queries from "../modules/portal/alumni/queries.js";
import type * as modules_portal_index from "../modules/portal/index.js";
import type * as modules_portal_parent_index from "../modules/portal/parent/index.js";
import type * as modules_portal_parent_mutations from "../modules/portal/parent/mutations.js";
import type * as modules_portal_parent_queries from "../modules/portal/parent/queries.js";
import type * as modules_portal_partner_index from "../modules/portal/partner/index.js";
import type * as modules_portal_partner_mutations from "../modules/portal/partner/mutations.js";
import type * as modules_portal_partner_queries from "../modules/portal/partner/queries.js";
import type * as modules_portal_student_index from "../modules/portal/student/index.js";
import type * as modules_portal_student_mutations from "../modules/portal/student/mutations.js";
import type * as modules_portal_student_queries from "../modules/portal/student/queries.js";
import type * as modules_sis_mutations from "../modules/sis/mutations.js";
import type * as modules_sis_queries from "../modules/sis/queries.js";
import type * as modules_sis_studentQueries from "../modules/sis/studentQueries.js";
import type * as modules_tasks_mutations from "../modules/tasks/mutations.js";
import type * as modules_tasks_queries from "../modules/tasks/queries.js";
import type * as modules_timetable_index from "../modules/timetable/index.js";
import type * as modules_timetable_mutations from "../modules/timetable/mutations.js";
import type * as modules_timetable_queries from "../modules/timetable/queries.js";
import type * as modules_transport_mutations from "../modules/transport/mutations.js";
import type * as modules_transport_queries from "../modules/transport/queries.js";
import type * as notifications from "../notifications.js";
import type * as organizations from "../organizations.js";
import type * as platform_analytics_index from "../platform/analytics/index.js";
import type * as platform_analytics_mutations from "../platform/analytics/mutations.js";
import type * as platform_analytics_queries from "../platform/analytics/queries.js";
import type * as platform_apiKeys_index from "../platform/apiKeys/index.js";
import type * as platform_apiKeys_mutations from "../platform/apiKeys/mutations.js";
import type * as platform_apiKeys_queries from "../platform/apiKeys/queries.js";
import type * as platform_audit_index from "../platform/audit/index.js";
import type * as platform_audit_queries from "../platform/audit/queries.js";
import type * as platform_automation_index from "../platform/automation/index.js";
import type * as platform_automation_mutations from "../platform/automation/mutations.js";
import type * as platform_automation_queries from "../platform/automation/queries.js";
import type * as platform_billing_index from "../platform/billing/index.js";
import type * as platform_billing_mutations from "../platform/billing/mutations.js";
import type * as platform_billing_queries from "../platform/billing/queries.js";
import type * as platform_changelog_index from "../platform/changelog/index.js";
import type * as platform_changelog_mutations from "../platform/changelog/mutations.js";
import type * as platform_changelog_queries from "../platform/changelog/queries.js";
import type * as platform_communications_index from "../platform/communications/index.js";
import type * as platform_communications_mutations from "../platform/communications/mutations.js";
import type * as platform_communications_queries from "../platform/communications/queries.js";
import type * as platform_crm_index from "../platform/crm/index.js";
import type * as platform_crm_mutations from "../platform/crm/mutations.js";
import type * as platform_crm_proposalMutations from "../platform/crm/proposalMutations.js";
import type * as platform_crm_proposalQueries from "../platform/crm/proposalQueries.js";
import type * as platform_crm_queries from "../platform/crm/queries.js";
import type * as platform_dashboard_index from "../platform/dashboard/index.js";
import type * as platform_dashboard_queries from "../platform/dashboard/queries.js";
import type * as platform_dataExport_index from "../platform/dataExport/index.js";
import type * as platform_dataExport_mutations from "../platform/dataExport/mutations.js";
import type * as platform_dataExport_queries from "../platform/dataExport/queries.js";
import type * as platform_featureFlags_index from "../platform/featureFlags/index.js";
import type * as platform_featureFlags_mutations from "../platform/featureFlags/mutations.js";
import type * as platform_featureFlags_queries from "../platform/featureFlags/queries.js";
import type * as platform_files_index from "../platform/files/index.js";
import type * as platform_files_mutations from "../platform/files/mutations.js";
import type * as platform_files_queries from "../platform/files/queries.js";
import type * as platform_health_index from "../platform/health/index.js";
import type * as platform_health_mutations from "../platform/health/mutations.js";
import type * as platform_health_queries from "../platform/health/queries.js";
import type * as platform_impersonation_index from "../platform/impersonation/index.js";
import type * as platform_impersonation_mutations from "../platform/impersonation/mutations.js";
import type * as platform_impersonation_queries from "../platform/impersonation/queries.js";
import type * as platform_index from "../platform/index.js";
import type * as platform_integration_index from "../platform/integration/index.js";
import type * as platform_integration_mutations from "../platform/integration/mutations.js";
import type * as platform_integration_queries from "../platform/integration/queries.js";
import type * as platform_knowledgeBase_index from "../platform/knowledgeBase/index.js";
import type * as platform_knowledgeBase_mutations from "../platform/knowledgeBase/mutations.js";
import type * as platform_knowledgeBase_queries from "../platform/knowledgeBase/queries.js";
import type * as platform_marketplace_index from "../platform/marketplace/index.js";
import type * as platform_marketplace_mutations from "../platform/marketplace/mutations.js";
import type * as platform_marketplace_payments from "../platform/marketplace/payments.js";
import type * as platform_marketplace_queries from "../platform/marketplace/queries.js";
import type * as platform_notifications_index from "../platform/notifications/index.js";
import type * as platform_notifications_mutations from "../platform/notifications/mutations.js";
import type * as platform_notifications_queries from "../platform/notifications/queries.js";
import type * as platform_onboarding_index from "../platform/onboarding/index.js";
import type * as platform_onboarding_mutations from "../platform/onboarding/mutations.js";
import type * as platform_onboarding_queries from "../platform/onboarding/queries.js";
import type * as platform_operations_index from "../platform/operations/index.js";
import type * as platform_operations_mutations from "../platform/operations/mutations.js";
import type * as platform_operations_queries from "../platform/operations/queries.js";
import type * as platform_roleBuilder_index from "../platform/roleBuilder/index.js";
import type * as platform_roleBuilder_mutations from "../platform/roleBuilder/mutations.js";
import type * as platform_roleBuilder_queries from "../platform/roleBuilder/queries.js";
import type * as platform_scheduledReports_index from "../platform/scheduledReports/index.js";
import type * as platform_scheduledReports_mutations from "../platform/scheduledReports/mutations.js";
import type * as platform_scheduledReports_queries from "../platform/scheduledReports/queries.js";
import type * as platform_security_index from "../platform/security/index.js";
import type * as platform_security_mutations from "../platform/security/mutations.js";
import type * as platform_security_queries from "../platform/security/queries.js";
import type * as platform_settings_index from "../platform/settings/index.js";
import type * as platform_settings_maintenanceCheck from "../platform/settings/maintenanceCheck.js";
import type * as platform_settings_mutations from "../platform/settings/mutations.js";
import type * as platform_settings_queries from "../platform/settings/queries.js";
import type * as platform_sla_index from "../platform/sla/index.js";
import type * as platform_sla_mutations from "../platform/sla/mutations.js";
import type * as platform_sla_queries from "../platform/sla/queries.js";
import type * as platform_staffPerformance_index from "../platform/staffPerformance/index.js";
import type * as platform_staffPerformance_mutations from "../platform/staffPerformance/mutations.js";
import type * as platform_staffPerformance_queries from "../platform/staffPerformance/queries.js";
import type * as platform_support_index from "../platform/support/index.js";
import type * as platform_support_mutations from "../platform/support/mutations.js";
import type * as platform_support_queries from "../platform/support/queries.js";
import type * as platform_tenantSuccess_index from "../platform/tenantSuccess/index.js";
import type * as platform_tenantSuccess_mutations from "../platform/tenantSuccess/mutations.js";
import type * as platform_tenantSuccess_queries from "../platform/tenantSuccess/queries.js";
import type * as platform_tenants_emailActions from "../platform/tenants/emailActions.js";
import type * as platform_tenants_index from "../platform/tenants/index.js";
import type * as platform_tenants_mutations from "../platform/tenants/mutations.js";
import type * as platform_tenants_queries from "../platform/tenants/queries.js";
import type * as platform_users_index from "../platform/users/index.js";
import type * as platform_users_mutations from "../platform/users/mutations.js";
import type * as platform_users_queries from "../platform/users/queries.js";
import type * as platform_users_utils from "../platform/users/utils.js";
import type * as platform_webhooks_index from "../platform/webhooks/index.js";
import type * as platform_webhooks_mutations from "../platform/webhooks/mutations.js";
import type * as platform_webhooks_queries from "../platform/webhooks/queries.js";
import type * as platform_whiteLabel_index from "../platform/whiteLabel/index.js";
import type * as platform_whiteLabel_mutations from "../platform/whiteLabel/mutations.js";
import type * as platform_whiteLabel_queries from "../platform/whiteLabel/queries.js";
import type * as sessions from "../sessions.js";
import type * as system_maintenance from "../system/maintenance.js";
import type * as tenants from "../tenants.js";
import type * as tickets from "../tickets.js";
import type * as users from "../users.js";
import type * as waitlist from "../waitlist.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "actions/ai/index": typeof actions_ai_index;
  "actions/ai/support": typeof actions_ai_support;
  "actions/auth/password": typeof actions_auth_password;
  "actions/auth/twoFactor": typeof actions_auth_twoFactor;
  "actions/communications/email": typeof actions_communications_email;
  "actions/communications/push": typeof actions_communications_push;
  "actions/communications/sms": typeof actions_communications_sms;
  "actions/payments/airtel": typeof actions_payments_airtel;
  "actions/payments/bankTransfer": typeof actions_payments_bankTransfer;
  "actions/payments/mpesa": typeof actions_payments_mpesa;
  "actions/payments/stripe": typeof actions_payments_stripe;
  auth: typeof auth;
  crons: typeof crons;
  "dev/seed": typeof dev_seed;
  "helpers/auditLog": typeof helpers_auditLog;
  "helpers/authorize": typeof helpers_authorize;
  "helpers/idGenerator": typeof helpers_idGenerator;
  "helpers/moduleGuard": typeof helpers_moduleGuard;
  "helpers/phoneUtils": typeof helpers_phoneUtils;
  "helpers/platformGuard": typeof helpers_platformGuard;
  "helpers/publisherGuard": typeof helpers_publisherGuard;
  "helpers/tenantGuard": typeof helpers_tenantGuard;
  http: typeof http;
  index: typeof index;
  "modules/academics/assignments": typeof modules_academics_assignments;
  "modules/academics/index": typeof modules_academics_index;
  "modules/academics/mutations": typeof modules_academics_mutations;
  "modules/academics/queries": typeof modules_academics_queries;
  "modules/admissions/index": typeof modules_admissions_index;
  "modules/admissions/mutations": typeof modules_admissions_mutations;
  "modules/admissions/queries": typeof modules_admissions_queries;
  "modules/auth/loginAttempts": typeof modules_auth_loginAttempts;
  "modules/auth/passwordHelpers": typeof modules_auth_passwordHelpers;
  "modules/auth/passwordPolicy": typeof modules_auth_passwordPolicy;
  "modules/auth/twoFactorHelpers": typeof modules_auth_twoFactorHelpers;
  "modules/communications/email": typeof modules_communications_email;
  "modules/communications/emailTemplates": typeof modules_communications_emailTemplates;
  "modules/communications/index": typeof modules_communications_index;
  "modules/communications/mutations": typeof modules_communications_mutations;
  "modules/communications/platform": typeof modules_communications_platform;
  "modules/communications/platformInviteEmails": typeof modules_communications_platformInviteEmails;
  "modules/communications/queries": typeof modules_communications_queries;
  "modules/communications/sms": typeof modules_communications_sms;
  "modules/communications/templates": typeof modules_communications_templates;
  "modules/communications/workos": typeof modules_communications_workos;
  "modules/ecommerce/index": typeof modules_ecommerce_index;
  "modules/ecommerce/mutations": typeof modules_ecommerce_mutations;
  "modules/ecommerce/queries": typeof modules_ecommerce_queries;
  "modules/ewallet/index": typeof modules_ewallet_index;
  "modules/ewallet/mutations": typeof modules_ewallet_mutations;
  "modules/ewallet/queries": typeof modules_ewallet_queries;
  "modules/finance/actions": typeof modules_finance_actions;
  "modules/finance/index": typeof modules_finance_index;
  "modules/finance/mutations": typeof modules_finance_mutations;
  "modules/finance/paymentUtils": typeof modules_finance_paymentUtils;
  "modules/finance/queries": typeof modules_finance_queries;
  "modules/hr/index": typeof modules_hr_index;
  "modules/hr/mutations": typeof modules_hr_mutations;
  "modules/hr/queries": typeof modules_hr_queries;
  "modules/library/index": typeof modules_library_index;
  "modules/library/mutations": typeof modules_library_mutations;
  "modules/library/queries": typeof modules_library_queries;
  "modules/marketplace/analytics": typeof modules_marketplace_analytics;
  "modules/marketplace/flags": typeof modules_marketplace_flags;
  "modules/marketplace/moduleDefinitions": typeof modules_marketplace_moduleDefinitions;
  "modules/marketplace/modules": typeof modules_marketplace_modules;
  "modules/marketplace/mutations": typeof modules_marketplace_mutations;
  "modules/marketplace/platform": typeof modules_marketplace_platform;
  "modules/marketplace/publisherOps": typeof modules_marketplace_publisherOps;
  "modules/marketplace/publishers": typeof modules_marketplace_publishers;
  "modules/marketplace/queries": typeof modules_marketplace_queries;
  "modules/marketplace/reviews": typeof modules_marketplace_reviews;
  "modules/marketplace/seed": typeof modules_marketplace_seed;
  "modules/marketplace/tierModules": typeof modules_marketplace_tierModules;
  "modules/notes/index": typeof modules_notes_index;
  "modules/notes/mutations": typeof modules_notes_mutations;
  "modules/notes/queries": typeof modules_notes_queries;
  "modules/platform/announcements": typeof modules_platform_announcements;
  "modules/platform/crm": typeof modules_platform_crm;
  "modules/platform/currency": typeof modules_platform_currency;
  "modules/platform/onboarding": typeof modules_platform_onboarding;
  "modules/platform/ops": typeof modules_platform_ops;
  "modules/platform/pilotGrants": typeof modules_platform_pilotGrants;
  "modules/platform/rbac": typeof modules_platform_rbac;
  "modules/platform/subscriptions": typeof modules_platform_subscriptions;
  "modules/platform/support": typeof modules_platform_support;
  "modules/platform/users": typeof modules_platform_users;
  "modules/platform/waitlist": typeof modules_platform_waitlist;
  "modules/pm/deploys": typeof modules_pm_deploys;
  "modules/pm/epics": typeof modules_pm_epics;
  "modules/pm/github": typeof modules_pm_github;
  "modules/pm/index": typeof modules_pm_index;
  "modules/pm/projects": typeof modules_pm_projects;
  "modules/pm/roles": typeof modules_pm_roles;
  "modules/pm/tasks": typeof modules_pm_tasks;
  "modules/pm/timeLogs": typeof modules_pm_timeLogs;
  "modules/pm/workspaces": typeof modules_pm_workspaces;
  "modules/portal/alumni/mutations": typeof modules_portal_alumni_mutations;
  "modules/portal/alumni/queries": typeof modules_portal_alumni_queries;
  "modules/portal/index": typeof modules_portal_index;
  "modules/portal/parent/index": typeof modules_portal_parent_index;
  "modules/portal/parent/mutations": typeof modules_portal_parent_mutations;
  "modules/portal/parent/queries": typeof modules_portal_parent_queries;
  "modules/portal/partner/index": typeof modules_portal_partner_index;
  "modules/portal/partner/mutations": typeof modules_portal_partner_mutations;
  "modules/portal/partner/queries": typeof modules_portal_partner_queries;
  "modules/portal/student/index": typeof modules_portal_student_index;
  "modules/portal/student/mutations": typeof modules_portal_student_mutations;
  "modules/portal/student/queries": typeof modules_portal_student_queries;
  "modules/sis/mutations": typeof modules_sis_mutations;
  "modules/sis/queries": typeof modules_sis_queries;
  "modules/sis/studentQueries": typeof modules_sis_studentQueries;
  "modules/tasks/mutations": typeof modules_tasks_mutations;
  "modules/tasks/queries": typeof modules_tasks_queries;
  "modules/timetable/index": typeof modules_timetable_index;
  "modules/timetable/mutations": typeof modules_timetable_mutations;
  "modules/timetable/queries": typeof modules_timetable_queries;
  "modules/transport/mutations": typeof modules_transport_mutations;
  "modules/transport/queries": typeof modules_transport_queries;
  notifications: typeof notifications;
  organizations: typeof organizations;
  "platform/analytics/index": typeof platform_analytics_index;
  "platform/analytics/mutations": typeof platform_analytics_mutations;
  "platform/analytics/queries": typeof platform_analytics_queries;
  "platform/apiKeys/index": typeof platform_apiKeys_index;
  "platform/apiKeys/mutations": typeof platform_apiKeys_mutations;
  "platform/apiKeys/queries": typeof platform_apiKeys_queries;
  "platform/audit/index": typeof platform_audit_index;
  "platform/audit/queries": typeof platform_audit_queries;
  "platform/automation/index": typeof platform_automation_index;
  "platform/automation/mutations": typeof platform_automation_mutations;
  "platform/automation/queries": typeof platform_automation_queries;
  "platform/billing/index": typeof platform_billing_index;
  "platform/billing/mutations": typeof platform_billing_mutations;
  "platform/billing/queries": typeof platform_billing_queries;
  "platform/changelog/index": typeof platform_changelog_index;
  "platform/changelog/mutations": typeof platform_changelog_mutations;
  "platform/changelog/queries": typeof platform_changelog_queries;
  "platform/communications/index": typeof platform_communications_index;
  "platform/communications/mutations": typeof platform_communications_mutations;
  "platform/communications/queries": typeof platform_communications_queries;
  "platform/crm/index": typeof platform_crm_index;
  "platform/crm/mutations": typeof platform_crm_mutations;
  "platform/crm/proposalMutations": typeof platform_crm_proposalMutations;
  "platform/crm/proposalQueries": typeof platform_crm_proposalQueries;
  "platform/crm/queries": typeof platform_crm_queries;
  "platform/dashboard/index": typeof platform_dashboard_index;
  "platform/dashboard/queries": typeof platform_dashboard_queries;
  "platform/dataExport/index": typeof platform_dataExport_index;
  "platform/dataExport/mutations": typeof platform_dataExport_mutations;
  "platform/dataExport/queries": typeof platform_dataExport_queries;
  "platform/featureFlags/index": typeof platform_featureFlags_index;
  "platform/featureFlags/mutations": typeof platform_featureFlags_mutations;
  "platform/featureFlags/queries": typeof platform_featureFlags_queries;
  "platform/files/index": typeof platform_files_index;
  "platform/files/mutations": typeof platform_files_mutations;
  "platform/files/queries": typeof platform_files_queries;
  "platform/health/index": typeof platform_health_index;
  "platform/health/mutations": typeof platform_health_mutations;
  "platform/health/queries": typeof platform_health_queries;
  "platform/impersonation/index": typeof platform_impersonation_index;
  "platform/impersonation/mutations": typeof platform_impersonation_mutations;
  "platform/impersonation/queries": typeof platform_impersonation_queries;
  "platform/index": typeof platform_index;
  "platform/integration/index": typeof platform_integration_index;
  "platform/integration/mutations": typeof platform_integration_mutations;
  "platform/integration/queries": typeof platform_integration_queries;
  "platform/knowledgeBase/index": typeof platform_knowledgeBase_index;
  "platform/knowledgeBase/mutations": typeof platform_knowledgeBase_mutations;
  "platform/knowledgeBase/queries": typeof platform_knowledgeBase_queries;
  "platform/marketplace/index": typeof platform_marketplace_index;
  "platform/marketplace/mutations": typeof platform_marketplace_mutations;
  "platform/marketplace/payments": typeof platform_marketplace_payments;
  "platform/marketplace/queries": typeof platform_marketplace_queries;
  "platform/notifications/index": typeof platform_notifications_index;
  "platform/notifications/mutations": typeof platform_notifications_mutations;
  "platform/notifications/queries": typeof platform_notifications_queries;
  "platform/onboarding/index": typeof platform_onboarding_index;
  "platform/onboarding/mutations": typeof platform_onboarding_mutations;
  "platform/onboarding/queries": typeof platform_onboarding_queries;
  "platform/operations/index": typeof platform_operations_index;
  "platform/operations/mutations": typeof platform_operations_mutations;
  "platform/operations/queries": typeof platform_operations_queries;
  "platform/roleBuilder/index": typeof platform_roleBuilder_index;
  "platform/roleBuilder/mutations": typeof platform_roleBuilder_mutations;
  "platform/roleBuilder/queries": typeof platform_roleBuilder_queries;
  "platform/scheduledReports/index": typeof platform_scheduledReports_index;
  "platform/scheduledReports/mutations": typeof platform_scheduledReports_mutations;
  "platform/scheduledReports/queries": typeof platform_scheduledReports_queries;
  "platform/security/index": typeof platform_security_index;
  "platform/security/mutations": typeof platform_security_mutations;
  "platform/security/queries": typeof platform_security_queries;
  "platform/settings/index": typeof platform_settings_index;
  "platform/settings/maintenanceCheck": typeof platform_settings_maintenanceCheck;
  "platform/settings/mutations": typeof platform_settings_mutations;
  "platform/settings/queries": typeof platform_settings_queries;
  "platform/sla/index": typeof platform_sla_index;
  "platform/sla/mutations": typeof platform_sla_mutations;
  "platform/sla/queries": typeof platform_sla_queries;
  "platform/staffPerformance/index": typeof platform_staffPerformance_index;
  "platform/staffPerformance/mutations": typeof platform_staffPerformance_mutations;
  "platform/staffPerformance/queries": typeof platform_staffPerformance_queries;
  "platform/support/index": typeof platform_support_index;
  "platform/support/mutations": typeof platform_support_mutations;
  "platform/support/queries": typeof platform_support_queries;
  "platform/tenantSuccess/index": typeof platform_tenantSuccess_index;
  "platform/tenantSuccess/mutations": typeof platform_tenantSuccess_mutations;
  "platform/tenantSuccess/queries": typeof platform_tenantSuccess_queries;
  "platform/tenants/emailActions": typeof platform_tenants_emailActions;
  "platform/tenants/index": typeof platform_tenants_index;
  "platform/tenants/mutations": typeof platform_tenants_mutations;
  "platform/tenants/queries": typeof platform_tenants_queries;
  "platform/users/index": typeof platform_users_index;
  "platform/users/mutations": typeof platform_users_mutations;
  "platform/users/queries": typeof platform_users_queries;
  "platform/users/utils": typeof platform_users_utils;
  "platform/webhooks/index": typeof platform_webhooks_index;
  "platform/webhooks/mutations": typeof platform_webhooks_mutations;
  "platform/webhooks/queries": typeof platform_webhooks_queries;
  "platform/whiteLabel/index": typeof platform_whiteLabel_index;
  "platform/whiteLabel/mutations": typeof platform_whiteLabel_mutations;
  "platform/whiteLabel/queries": typeof platform_whiteLabel_queries;
  sessions: typeof sessions;
  "system/maintenance": typeof system_maintenance;
  tenants: typeof tenants;
  tickets: typeof tickets;
  users: typeof users;
  waitlist: typeof waitlist;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
