/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as actions_ai_index from "../actions/ai/index.js";
import type * as actions_ai_support from "../actions/ai/support.js";
import type * as actions_auth_password from "../actions/auth/password.js";
import type * as actions_auth_twoFactor from "../actions/auth/twoFactor.js";
import type * as actions_auth_workos from "../actions/auth/workos.js";
import type * as actions_communications_email from "../actions/communications/email.js";
import type * as actions_communications_push from "../actions/communications/push.js";
import type * as actions_communications_sms from "../actions/communications/sms.js";
import type * as actions_payments_airtel from "../actions/payments/airtel.js";
import type * as actions_payments_bankTransfer from "../actions/payments/bankTransfer.js";
import type * as actions_payments_mpesa from "../actions/payments/mpesa.js";
import type * as actions_payments_stripe from "../actions/payments/stripe.js";
import type * as auth from "../auth.js";
import type * as crons from "../crons.js";
import type * as dev_seed from "../dev/seed.js";
import type * as emails__base from "../emails/_base.js";
import type * as emails_activation_congratulations from "../emails/activation_congratulations.js";
import type * as emails_parent_invite_email from "../emails/parent_invite_email.js";
import type * as emails_registry from "../emails/registry.js";
import type * as emails_staff_invite from "../emails/staff_invite.js";
import type * as emails_stalled_onboarding_nudge from "../emails/stalled_onboarding_nudge.js";
import type * as emails_subscription_confirmed from "../emails/subscription_confirmed.js";
import type * as emails_tenant_invite from "../emails/tenant_invite.js";
import type * as emails_tenant_invite_reminder_day3 from "../emails/tenant_invite_reminder_day3.js";
import type * as emails_tenant_invite_reminder_day6 from "../emails/tenant_invite_reminder_day6.js";
import type * as emails_tenant_welcome from "../emails/tenant_welcome.js";
import type * as emails_trial_day10_nudge from "../emails/trial_day10_nudge.js";
import type * as emails_trial_day12_outreach from "../emails/trial_day12_outreach.js";
import type * as emails_trial_day13_urgent from "../emails/trial_day13_urgent.js";
import type * as emails_trial_day3_checkin from "../emails/trial_day3_checkin.js";
import type * as emails_trial_day7_halfway from "../emails/trial_day7_halfway.js";
import type * as emails_trial_expired from "../emails/trial_expired.js";
import type * as emails_waitlist_confirmation from "../emails/waitlist_confirmation.js";
import type * as eventBus from "../eventBus.js";
import type * as helpers_auditLog from "../helpers/auditLog.js";
import type * as helpers_authorize from "../helpers/authorize.js";
import type * as helpers_idGenerator from "../helpers/idGenerator.js";
import type * as helpers_moduleGuard from "../helpers/moduleGuard.js";
import type * as helpers_phoneUtils from "../helpers/phoneUtils.js";
import type * as helpers_platformGuard from "../helpers/platformGuard.js";
import type * as helpers_publisherGuard from "../helpers/publisherGuard.js";
import type * as helpers_resellerGuard from "../helpers/resellerGuard.js";
import type * as helpers_tenantGuard from "../helpers/tenantGuard.js";
import type * as http from "../http.js";
import type * as index from "../index.js";
import type * as modules_academics_assignments from "../modules/academics/assignments.js";
import type * as modules_academics_configSchema from "../modules/academics/configSchema.js";
import type * as modules_academics_eventHandlers from "../modules/academics/eventHandlers.js";
import type * as modules_academics_features from "../modules/academics/features.js";
import type * as modules_academics_index from "../modules/academics/index.js";
import type * as modules_academics_mutations from "../modules/academics/mutations.js";
import type * as modules_academics_notifications from "../modules/academics/notifications.js";
import type * as modules_academics_onInstall from "../modules/academics/onInstall.js";
import type * as modules_academics_onUninstall from "../modules/academics/onUninstall.js";
import type * as modules_academics_publicApi from "../modules/academics/publicApi.js";
import type * as modules_academics_queries from "../modules/academics/queries.js";
import type * as modules_admissions_configSchema from "../modules/admissions/configSchema.js";
import type * as modules_admissions_eventHandlers from "../modules/admissions/eventHandlers.js";
import type * as modules_admissions_features from "../modules/admissions/features.js";
import type * as modules_admissions_index from "../modules/admissions/index.js";
import type * as modules_admissions_mutations from "../modules/admissions/mutations.js";
import type * as modules_admissions_notifications from "../modules/admissions/notifications.js";
import type * as modules_admissions_onInstall from "../modules/admissions/onInstall.js";
import type * as modules_admissions_onUninstall from "../modules/admissions/onUninstall.js";
import type * as modules_admissions_publicApi from "../modules/admissions/publicApi.js";
import type * as modules_admissions_queries from "../modules/admissions/queries.js";
import type * as modules_advanced_analytics_configSchema from "../modules/advanced_analytics/configSchema.js";
import type * as modules_advanced_analytics_eventHandlers from "../modules/advanced_analytics/eventHandlers.js";
import type * as modules_advanced_analytics_features from "../modules/advanced_analytics/features.js";
import type * as modules_advanced_analytics_index from "../modules/advanced_analytics/index.js";
import type * as modules_advanced_analytics_notifications from "../modules/advanced_analytics/notifications.js";
import type * as modules_advanced_analytics_onInstall from "../modules/advanced_analytics/onInstall.js";
import type * as modules_advanced_analytics_onUninstall from "../modules/advanced_analytics/onUninstall.js";
import type * as modules_advanced_analytics_publicApi from "../modules/advanced_analytics/publicApi.js";
import type * as modules_alumni_configSchema from "../modules/alumni/configSchema.js";
import type * as modules_alumni_eventHandlers from "../modules/alumni/eventHandlers.js";
import type * as modules_alumni_features from "../modules/alumni/features.js";
import type * as modules_alumni_index from "../modules/alumni/index.js";
import type * as modules_alumni_notifications from "../modules/alumni/notifications.js";
import type * as modules_alumni_onInstall from "../modules/alumni/onInstall.js";
import type * as modules_alumni_onUninstall from "../modules/alumni/onUninstall.js";
import type * as modules_alumni_publicApi from "../modules/alumni/publicApi.js";
import type * as modules_attendance_configSchema from "../modules/attendance/configSchema.js";
import type * as modules_attendance_eventHandlers from "../modules/attendance/eventHandlers.js";
import type * as modules_attendance_features from "../modules/attendance/features.js";
import type * as modules_attendance_index from "../modules/attendance/index.js";
import type * as modules_attendance_notifications from "../modules/attendance/notifications.js";
import type * as modules_attendance_onInstall from "../modules/attendance/onInstall.js";
import type * as modules_attendance_onUninstall from "../modules/attendance/onUninstall.js";
import type * as modules_attendance_publicApi from "../modules/attendance/publicApi.js";
import type * as modules_auth_loginAttempts from "../modules/auth/loginAttempts.js";
import type * as modules_auth_passwordHelpers from "../modules/auth/passwordHelpers.js";
import type * as modules_auth_passwordPolicy from "../modules/auth/passwordPolicy.js";
import type * as modules_auth_twoFactorHelpers from "../modules/auth/twoFactorHelpers.js";
import type * as modules_communications_configSchema from "../modules/communications/configSchema.js";
import type * as modules_communications_email from "../modules/communications/email.js";
import type * as modules_communications_emailTemplates from "../modules/communications/emailTemplates.js";
import type * as modules_communications_eventHandlers from "../modules/communications/eventHandlers.js";
import type * as modules_communications_features from "../modules/communications/features.js";
import type * as modules_communications_index from "../modules/communications/index.js";
import type * as modules_communications_mutations from "../modules/communications/mutations.js";
import type * as modules_communications_notifications from "../modules/communications/notifications.js";
import type * as modules_communications_onInstall from "../modules/communications/onInstall.js";
import type * as modules_communications_onUninstall from "../modules/communications/onUninstall.js";
import type * as modules_communications_platform from "../modules/communications/platform.js";
import type * as modules_communications_platformInviteEmails from "../modules/communications/platformInviteEmails.js";
import type * as modules_communications_queries from "../modules/communications/queries.js";
import type * as modules_communications_sms from "../modules/communications/sms.js";
import type * as modules_communications_templates from "../modules/communications/templates.js";
import type * as modules_communications_workos from "../modules/communications/workos.js";
import type * as modules_ecommerce_index from "../modules/ecommerce/index.js";
import type * as modules_ecommerce_mutations from "../modules/ecommerce/mutations.js";
import type * as modules_ecommerce_notifications from "../modules/ecommerce/notifications.js";
import type * as modules_ecommerce_onInstall from "../modules/ecommerce/onInstall.js";
import type * as modules_ecommerce_onUninstall from "../modules/ecommerce/onUninstall.js";
import type * as modules_ecommerce_publicApi from "../modules/ecommerce/publicApi.js";
import type * as modules_ecommerce_queries from "../modules/ecommerce/queries.js";
import type * as modules_ewallet_configSchema from "../modules/ewallet/configSchema.js";
import type * as modules_ewallet_eventHandlers from "../modules/ewallet/eventHandlers.js";
import type * as modules_ewallet_features from "../modules/ewallet/features.js";
import type * as modules_ewallet_index from "../modules/ewallet/index.js";
import type * as modules_ewallet_mutations from "../modules/ewallet/mutations.js";
import type * as modules_ewallet_notifications from "../modules/ewallet/notifications.js";
import type * as modules_ewallet_onInstall from "../modules/ewallet/onInstall.js";
import type * as modules_ewallet_onUninstall from "../modules/ewallet/onUninstall.js";
import type * as modules_ewallet_publicApi from "../modules/ewallet/publicApi.js";
import type * as modules_ewallet_queries from "../modules/ewallet/queries.js";
import type * as modules_finance_actions from "../modules/finance/actions.js";
import type * as modules_finance_configSchema from "../modules/finance/configSchema.js";
import type * as modules_finance_eventHandlers from "../modules/finance/eventHandlers.js";
import type * as modules_finance_features from "../modules/finance/features.js";
import type * as modules_finance_index from "../modules/finance/index.js";
import type * as modules_finance_mutations from "../modules/finance/mutations.js";
import type * as modules_finance_notifications from "../modules/finance/notifications.js";
import type * as modules_finance_onInstall from "../modules/finance/onInstall.js";
import type * as modules_finance_onUninstall from "../modules/finance/onUninstall.js";
import type * as modules_finance_paymentUtils from "../modules/finance/paymentUtils.js";
import type * as modules_finance_publicApi from "../modules/finance/publicApi.js";
import type * as modules_finance_queries from "../modules/finance/queries.js";
import type * as modules_hr_configSchema from "../modules/hr/configSchema.js";
import type * as modules_hr_eventHandlers from "../modules/hr/eventHandlers.js";
import type * as modules_hr_features from "../modules/hr/features.js";
import type * as modules_hr_index from "../modules/hr/index.js";
import type * as modules_hr_mutations from "../modules/hr/mutations.js";
import type * as modules_hr_notifications from "../modules/hr/notifications.js";
import type * as modules_hr_onInstall from "../modules/hr/onInstall.js";
import type * as modules_hr_onUninstall from "../modules/hr/onUninstall.js";
import type * as modules_hr_publicApi from "../modules/hr/publicApi.js";
import type * as modules_hr_queries from "../modules/hr/queries.js";
import type * as modules_library_configSchema from "../modules/library/configSchema.js";
import type * as modules_library_eventHandlers from "../modules/library/eventHandlers.js";
import type * as modules_library_features from "../modules/library/features.js";
import type * as modules_library_index from "../modules/library/index.js";
import type * as modules_library_mutations from "../modules/library/mutations.js";
import type * as modules_library_notifications from "../modules/library/notifications.js";
import type * as modules_library_onInstall from "../modules/library/onInstall.js";
import type * as modules_library_onUninstall from "../modules/library/onUninstall.js";
import type * as modules_library_publicApi from "../modules/library/publicApi.js";
import type * as modules_library_queries from "../modules/library/queries.js";
import type * as modules_marketplace_analytics from "../modules/marketplace/analytics.js";
import type * as modules_marketplace_billing from "../modules/marketplace/billing.js";
import type * as modules_marketplace_flags from "../modules/marketplace/flags.js";
import type * as modules_marketplace_installation from "../modules/marketplace/installation.js";
import type * as modules_marketplace_moduleDefinitions from "../modules/marketplace/moduleDefinitions.js";
import type * as modules_marketplace_modules from "../modules/marketplace/modules.js";
import type * as modules_marketplace_mutations from "../modules/marketplace/mutations.js";
import type * as modules_marketplace_pilotGrants from "../modules/marketplace/pilotGrants.js";
import type * as modules_marketplace_planAudit from "../modules/marketplace/planAudit.js";
import type * as modules_marketplace_platform from "../modules/marketplace/platform.js";
import type * as modules_marketplace_platformDashboard from "../modules/marketplace/platformDashboard.js";
import type * as modules_marketplace_pricing from "../modules/marketplace/pricing.js";
import type * as modules_marketplace_publisherOps from "../modules/marketplace/publisherOps.js";
import type * as modules_marketplace_publishers from "../modules/marketplace/publishers.js";
import type * as modules_marketplace_queries from "../modules/marketplace/queries.js";
import type * as modules_marketplace_reviews from "../modules/marketplace/reviews.js";
import type * as modules_marketplace_seed from "../modules/marketplace/seed.js";
import type * as modules_marketplace_settings from "../modules/marketplace/settings.js";
import type * as modules_marketplace_tierModules from "../modules/marketplace/tierModules.js";
import type * as modules_moduleCatalog from "../modules/moduleCatalog.js";
import type * as modules_modulePublicApis from "../modules/modulePublicApis.js";
import type * as modules_moduleRuntime from "../modules/moduleRuntime.js";
import type * as modules_notes_index from "../modules/notes/index.js";
import type * as modules_notes_mutations from "../modules/notes/mutations.js";
import type * as modules_notes_queries from "../modules/notes/queries.js";
import type * as modules_parent_portal_configSchema from "../modules/parent_portal/configSchema.js";
import type * as modules_parent_portal_eventHandlers from "../modules/parent_portal/eventHandlers.js";
import type * as modules_parent_portal_features from "../modules/parent_portal/features.js";
import type * as modules_parent_portal_index from "../modules/parent_portal/index.js";
import type * as modules_parent_portal_notifications from "../modules/parent_portal/notifications.js";
import type * as modules_parent_portal_onInstall from "../modules/parent_portal/onInstall.js";
import type * as modules_parent_portal_onUninstall from "../modules/parent_portal/onUninstall.js";
import type * as modules_parent_portal_publicApi from "../modules/parent_portal/publicApi.js";
import type * as modules_partner_configSchema from "../modules/partner/configSchema.js";
import type * as modules_partner_eventHandlers from "../modules/partner/eventHandlers.js";
import type * as modules_partner_features from "../modules/partner/features.js";
import type * as modules_partner_index from "../modules/partner/index.js";
import type * as modules_partner_notifications from "../modules/partner/notifications.js";
import type * as modules_partner_onInstall from "../modules/partner/onInstall.js";
import type * as modules_partner_onUninstall from "../modules/partner/onUninstall.js";
import type * as modules_partner_publicApi from "../modules/partner/publicApi.js";
import type * as modules_platform_announcements from "../modules/platform/announcements.js";
import type * as modules_platform_crm from "../modules/platform/crm.js";
import type * as modules_platform_currency from "../modules/platform/currency.js";
import type * as modules_platform_onboarding from "../modules/platform/onboarding.js";
import type * as modules_platform_ops from "../modules/platform/ops.js";
import type * as modules_platform_pilotGrants from "../modules/platform/pilotGrants.js";
import type * as modules_platform_rbac from "../modules/platform/rbac.js";
import type * as modules_platform_subscriptions from "../modules/platform/subscriptions.js";
import type * as modules_platform_support from "../modules/platform/support.js";
import type * as modules_platform_users from "../modules/platform/users.js";
import type * as modules_platform_waitlist from "../modules/platform/waitlist.js";
import type * as modules_pm_deploys from "../modules/pm/deploys.js";
import type * as modules_pm_epics from "../modules/pm/epics.js";
import type * as modules_pm_github from "../modules/pm/github.js";
import type * as modules_pm_index from "../modules/pm/index.js";
import type * as modules_pm_projects from "../modules/pm/projects.js";
import type * as modules_pm_roles from "../modules/pm/roles.js";
import type * as modules_pm_tasks from "../modules/pm/tasks.js";
import type * as modules_pm_timeLogs from "../modules/pm/timeLogs.js";
import type * as modules_pm_workspaces from "../modules/pm/workspaces.js";
import type * as modules_portal_alumni_mutations from "../modules/portal/alumni/mutations.js";
import type * as modules_portal_alumni_queries from "../modules/portal/alumni/queries.js";
import type * as modules_portal_index from "../modules/portal/index.js";
import type * as modules_portal_parent_index from "../modules/portal/parent/index.js";
import type * as modules_portal_parent_mutations from "../modules/portal/parent/mutations.js";
import type * as modules_portal_parent_queries from "../modules/portal/parent/queries.js";
import type * as modules_portal_partner_index from "../modules/portal/partner/index.js";
import type * as modules_portal_partner_mutations from "../modules/portal/partner/mutations.js";
import type * as modules_portal_partner_queries from "../modules/portal/partner/queries.js";
import type * as modules_portal_student_index from "../modules/portal/student/index.js";
import type * as modules_portal_student_mutations from "../modules/portal/student/mutations.js";
import type * as modules_portal_student_queries from "../modules/portal/student/queries.js";
import type * as modules_publisher_index from "../modules/publisher/index.js";
import type * as modules_publisher_internal_crons from "../modules/publisher/internal/crons.js";
import type * as modules_publisher_mutations_analytics from "../modules/publisher/mutations/analytics.js";
import type * as modules_publisher_mutations_applications from "../modules/publisher/mutations/applications.js";
import type * as modules_publisher_mutations_modules from "../modules/publisher/mutations/modules.js";
import type * as modules_publisher_mutations_profile from "../modules/publisher/mutations/profile.js";
import type * as modules_publisher_mutations_support from "../modules/publisher/mutations/support.js";
import type * as modules_reseller_index from "../modules/reseller/index.js";
import type * as modules_reseller_internal_crons from "../modules/reseller/internal/crons.js";
import type * as modules_reseller_mutations_applications from "../modules/reseller/mutations/applications.js";
import type * as modules_reseller_mutations_commissions from "../modules/reseller/mutations/commissions.js";
import type * as modules_reseller_mutations_leads from "../modules/reseller/mutations/leads.js";
import type * as modules_reseller_mutations_marketing from "../modules/reseller/mutations/marketing.js";
import type * as modules_reseller_mutations_profile from "../modules/reseller/mutations/profile.js";
import type * as modules_reseller_queries_customers from "../modules/reseller/queries/customers.js";
import type * as modules_reseller_queries_orders from "../modules/reseller/queries/orders.js";
import type * as modules_reseller_queries_products from "../modules/reseller/queries/products.js";
import type * as modules_reseller_queries_referrals from "../modules/reseller/queries/referrals.js";
import type * as modules_reseller_queries_subdomain from "../modules/reseller/queries/subdomain.js";
import type * as modules_reseller_queries_support from "../modules/reseller/queries/support.js";
import type * as modules_sis_mutations from "../modules/sis/mutations.js";
import type * as modules_sis_queries from "../modules/sis/queries.js";
import type * as modules_sis_studentQueries from "../modules/sis/studentQueries.js";
import type * as modules_tasks_mutations from "../modules/tasks/mutations.js";
import type * as modules_tasks_queries from "../modules/tasks/queries.js";
import type * as modules_timetable_configSchema from "../modules/timetable/configSchema.js";
import type * as modules_timetable_eventHandlers from "../modules/timetable/eventHandlers.js";
import type * as modules_timetable_features from "../modules/timetable/features.js";
import type * as modules_timetable_index from "../modules/timetable/index.js";
import type * as modules_timetable_mutations from "../modules/timetable/mutations.js";
import type * as modules_timetable_notifications from "../modules/timetable/notifications.js";
import type * as modules_timetable_onInstall from "../modules/timetable/onInstall.js";
import type * as modules_timetable_onUninstall from "../modules/timetable/onUninstall.js";
import type * as modules_timetable_publicApi from "../modules/timetable/publicApi.js";
import type * as modules_timetable_queries from "../modules/timetable/queries.js";
import type * as modules_transport_configSchema from "../modules/transport/configSchema.js";
import type * as modules_transport_eventHandlers from "../modules/transport/eventHandlers.js";
import type * as modules_transport_features from "../modules/transport/features.js";
import type * as modules_transport_index from "../modules/transport/index.js";
import type * as modules_transport_mutations from "../modules/transport/mutations.js";
import type * as modules_transport_notifications from "../modules/transport/notifications.js";
import type * as modules_transport_onInstall from "../modules/transport/onInstall.js";
import type * as modules_transport_onUninstall from "../modules/transport/onUninstall.js";
import type * as modules_transport_publicApi from "../modules/transport/publicApi.js";
import type * as modules_transport_queries from "../modules/transport/queries.js";
import type * as notifications from "../notifications.js";
import type * as organizations from "../organizations.js";
import type * as parentOnboarding from "../parentOnboarding.js";
import type * as platform_analytics_index from "../platform/analytics/index.js";
import type * as platform_analytics_mutations from "../platform/analytics/mutations.js";
import type * as platform_analytics_queries from "../platform/analytics/queries.js";
import type * as platform_apiKeys_index from "../platform/apiKeys/index.js";
import type * as platform_apiKeys_mutations from "../platform/apiKeys/mutations.js";
import type * as platform_apiKeys_queries from "../platform/apiKeys/queries.js";
import type * as platform_audit_index from "../platform/audit/index.js";
import type * as platform_audit_queries from "../platform/audit/queries.js";
import type * as platform_automation_index from "../platform/automation/index.js";
import type * as platform_automation_mutations from "../platform/automation/mutations.js";
import type * as platform_automation_queries from "../platform/automation/queries.js";
import type * as platform_billing_index from "../platform/billing/index.js";
import type * as platform_billing_mutations from "../platform/billing/mutations.js";
import type * as platform_billing_queries from "../platform/billing/queries.js";
import type * as platform_changelog_index from "../platform/changelog/index.js";
import type * as platform_changelog_mutations from "../platform/changelog/mutations.js";
import type * as platform_changelog_queries from "../platform/changelog/queries.js";
import type * as platform_communications_index from "../platform/communications/index.js";
import type * as platform_communications_mutations from "../platform/communications/mutations.js";
import type * as platform_communications_queries from "../platform/communications/queries.js";
import type * as platform_crm_index from "../platform/crm/index.js";
import type * as platform_crm_mutations from "../platform/crm/mutations.js";
import type * as platform_crm_proposalMutations from "../platform/crm/proposalMutations.js";
import type * as platform_crm_proposalQueries from "../platform/crm/proposalQueries.js";
import type * as platform_crm_queries from "../platform/crm/queries.js";
import type * as platform_dashboard_index from "../platform/dashboard/index.js";
import type * as platform_dashboard_queries from "../platform/dashboard/queries.js";
import type * as platform_dataExport_index from "../platform/dataExport/index.js";
import type * as platform_dataExport_mutations from "../platform/dataExport/mutations.js";
import type * as platform_dataExport_queries from "../platform/dataExport/queries.js";
import type * as platform_featureFlags_index from "../platform/featureFlags/index.js";
import type * as platform_featureFlags_mutations from "../platform/featureFlags/mutations.js";
import type * as platform_featureFlags_queries from "../platform/featureFlags/queries.js";
import type * as platform_files_index from "../platform/files/index.js";
import type * as platform_files_mutations from "../platform/files/mutations.js";
import type * as platform_files_queries from "../platform/files/queries.js";
import type * as platform_health_index from "../platform/health/index.js";
import type * as platform_health_mutations from "../platform/health/mutations.js";
import type * as platform_health_queries from "../platform/health/queries.js";
import type * as platform_impersonation_index from "../platform/impersonation/index.js";
import type * as platform_impersonation_mutations from "../platform/impersonation/mutations.js";
import type * as platform_impersonation_queries from "../platform/impersonation/queries.js";
import type * as platform_index from "../platform/index.js";
import type * as platform_integration_index from "../platform/integration/index.js";
import type * as platform_integration_mutations from "../platform/integration/mutations.js";
import type * as platform_integration_queries from "../platform/integration/queries.js";
import type * as platform_knowledgeBase_index from "../platform/knowledgeBase/index.js";
import type * as platform_knowledgeBase_mutations from "../platform/knowledgeBase/mutations.js";
import type * as platform_knowledgeBase_queries from "../platform/knowledgeBase/queries.js";
import type * as platform_marketplace_index from "../platform/marketplace/index.js";
import type * as platform_marketplace_mutations from "../platform/marketplace/mutations.js";
import type * as platform_marketplace_payments from "../platform/marketplace/payments.js";
import type * as platform_marketplace_queries from "../platform/marketplace/queries.js";
import type * as platform_notifications_index from "../platform/notifications/index.js";
import type * as platform_notifications_mutations from "../platform/notifications/mutations.js";
import type * as platform_notifications_queries from "../platform/notifications/queries.js";
import type * as platform_onboarding_index from "../platform/onboarding/index.js";
import type * as platform_onboarding_mutations from "../platform/onboarding/mutations.js";
import type * as platform_onboarding_queries from "../platform/onboarding/queries.js";
import type * as platform_operations_index from "../platform/operations/index.js";
import type * as platform_operations_mutations from "../platform/operations/mutations.js";
import type * as platform_operations_queries from "../platform/operations/queries.js";
import type * as platform_resellers_mutations from "../platform/resellers/mutations.js";
import type * as platform_resellers_queries from "../platform/resellers/queries.js";
import type * as platform_roleBuilder_index from "../platform/roleBuilder/index.js";
import type * as platform_roleBuilder_mutations from "../platform/roleBuilder/mutations.js";
import type * as platform_roleBuilder_queries from "../platform/roleBuilder/queries.js";
import type * as platform_scheduledReports_index from "../platform/scheduledReports/index.js";
import type * as platform_scheduledReports_mutations from "../platform/scheduledReports/mutations.js";
import type * as platform_scheduledReports_queries from "../platform/scheduledReports/queries.js";
import type * as platform_security_index from "../platform/security/index.js";
import type * as platform_security_mutations from "../platform/security/mutations.js";
import type * as platform_security_queries from "../platform/security/queries.js";
import type * as platform_settings_index from "../platform/settings/index.js";
import type * as platform_settings_maintenanceCheck from "../platform/settings/maintenanceCheck.js";
import type * as platform_settings_mutations from "../platform/settings/mutations.js";
import type * as platform_settings_queries from "../platform/settings/queries.js";
import type * as platform_sla_index from "../platform/sla/index.js";
import type * as platform_sla_mutations from "../platform/sla/mutations.js";
import type * as platform_sla_queries from "../platform/sla/queries.js";
import type * as platform_staffPerformance_index from "../platform/staffPerformance/index.js";
import type * as platform_staffPerformance_mutations from "../platform/staffPerformance/mutations.js";
import type * as platform_staffPerformance_queries from "../platform/staffPerformance/queries.js";
import type * as platform_support_index from "../platform/support/index.js";
import type * as platform_support_mutations from "../platform/support/mutations.js";
import type * as platform_support_queries from "../platform/support/queries.js";
import type * as platform_tenantSuccess_index from "../platform/tenantSuccess/index.js";
import type * as platform_tenantSuccess_mutations from "../platform/tenantSuccess/mutations.js";
import type * as platform_tenantSuccess_queries from "../platform/tenantSuccess/queries.js";
import type * as platform_tenants_actions from "../platform/tenants/actions.js";
import type * as platform_tenants_emailActions from "../platform/tenants/emailActions.js";
import type * as platform_tenants_index from "../platform/tenants/index.js";
import type * as platform_tenants_mutations from "../platform/tenants/mutations.js";
import type * as platform_tenants_queries from "../platform/tenants/queries.js";
import type * as platform_users_index from "../platform/users/index.js";
import type * as platform_users_mutations from "../platform/users/mutations.js";
import type * as platform_users_queries from "../platform/users/queries.js";
import type * as platform_users_utils from "../platform/users/utils.js";
import type * as platform_webhooks_index from "../platform/webhooks/index.js";
import type * as platform_webhooks_mutations from "../platform/webhooks/mutations.js";
import type * as platform_webhooks_queries from "../platform/webhooks/queries.js";
import type * as platform_whiteLabel_index from "../platform/whiteLabel/index.js";
import type * as platform_whiteLabel_mutations from "../platform/whiteLabel/mutations.js";
import type * as platform_whiteLabel_queries from "../platform/whiteLabel/queries.js";
import type * as publicApplications from "../publicApplications.js";
import type * as sessions from "../sessions.js";
import type * as staffInvites from "../staffInvites.js";
import type * as system_maintenance from "../system/maintenance.js";
import type * as tenants from "../tenants.js";
import type * as tickets from "../tickets.js";
import type * as users from "../users.js";
import type * as waitlist from "../waitlist.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "actions/ai/index": typeof actions_ai_index;
  "actions/ai/support": typeof actions_ai_support;
  "actions/auth/password": typeof actions_auth_password;
  "actions/auth/twoFactor": typeof actions_auth_twoFactor;
  "actions/auth/workos": typeof actions_auth_workos;
  "actions/communications/email": typeof actions_communications_email;
  "actions/communications/push": typeof actions_communications_push;
  "actions/communications/sms": typeof actions_communications_sms;
  "actions/payments/airtel": typeof actions_payments_airtel;
  "actions/payments/bankTransfer": typeof actions_payments_bankTransfer;
  "actions/payments/mpesa": typeof actions_payments_mpesa;
  "actions/payments/stripe": typeof actions_payments_stripe;
  auth: typeof auth;
  crons: typeof crons;
  "dev/seed": typeof dev_seed;
  "emails/_base": typeof emails__base;
  "emails/activation_congratulations": typeof emails_activation_congratulations;
  "emails/parent_invite_email": typeof emails_parent_invite_email;
  "emails/registry": typeof emails_registry;
  "emails/staff_invite": typeof emails_staff_invite;
  "emails/stalled_onboarding_nudge": typeof emails_stalled_onboarding_nudge;
  "emails/subscription_confirmed": typeof emails_subscription_confirmed;
  "emails/tenant_invite": typeof emails_tenant_invite;
  "emails/tenant_invite_reminder_day3": typeof emails_tenant_invite_reminder_day3;
  "emails/tenant_invite_reminder_day6": typeof emails_tenant_invite_reminder_day6;
  "emails/tenant_welcome": typeof emails_tenant_welcome;
  "emails/trial_day10_nudge": typeof emails_trial_day10_nudge;
  "emails/trial_day12_outreach": typeof emails_trial_day12_outreach;
  "emails/trial_day13_urgent": typeof emails_trial_day13_urgent;
  "emails/trial_day3_checkin": typeof emails_trial_day3_checkin;
  "emails/trial_day7_halfway": typeof emails_trial_day7_halfway;
  "emails/trial_expired": typeof emails_trial_expired;
  "emails/waitlist_confirmation": typeof emails_waitlist_confirmation;
  eventBus: typeof eventBus;
  "helpers/auditLog": typeof helpers_auditLog;
  "helpers/authorize": typeof helpers_authorize;
  "helpers/idGenerator": typeof helpers_idGenerator;
  "helpers/moduleGuard": typeof helpers_moduleGuard;
  "helpers/phoneUtils": typeof helpers_phoneUtils;
  "helpers/platformGuard": typeof helpers_platformGuard;
  "helpers/publisherGuard": typeof helpers_publisherGuard;
  "helpers/resellerGuard": typeof helpers_resellerGuard;
  "helpers/tenantGuard": typeof helpers_tenantGuard;
  http: typeof http;
  index: typeof index;
  "modules/academics/assignments": typeof modules_academics_assignments;
  "modules/academics/configSchema": typeof modules_academics_configSchema;
  "modules/academics/eventHandlers": typeof modules_academics_eventHandlers;
  "modules/academics/features": typeof modules_academics_features;
  "modules/academics/index": typeof modules_academics_index;
  "modules/academics/mutations": typeof modules_academics_mutations;
  "modules/academics/notifications": typeof modules_academics_notifications;
  "modules/academics/onInstall": typeof modules_academics_onInstall;
  "modules/academics/onUninstall": typeof modules_academics_onUninstall;
  "modules/academics/publicApi": typeof modules_academics_publicApi;
  "modules/academics/queries": typeof modules_academics_queries;
  "modules/admissions/configSchema": typeof modules_admissions_configSchema;
  "modules/admissions/eventHandlers": typeof modules_admissions_eventHandlers;
  "modules/admissions/features": typeof modules_admissions_features;
  "modules/admissions/index": typeof modules_admissions_index;
  "modules/admissions/mutations": typeof modules_admissions_mutations;
  "modules/admissions/notifications": typeof modules_admissions_notifications;
  "modules/admissions/onInstall": typeof modules_admissions_onInstall;
  "modules/admissions/onUninstall": typeof modules_admissions_onUninstall;
  "modules/admissions/publicApi": typeof modules_admissions_publicApi;
  "modules/admissions/queries": typeof modules_admissions_queries;
  "modules/advanced_analytics/configSchema": typeof modules_advanced_analytics_configSchema;
  "modules/advanced_analytics/eventHandlers": typeof modules_advanced_analytics_eventHandlers;
  "modules/advanced_analytics/features": typeof modules_advanced_analytics_features;
  "modules/advanced_analytics/index": typeof modules_advanced_analytics_index;
  "modules/advanced_analytics/notifications": typeof modules_advanced_analytics_notifications;
  "modules/advanced_analytics/onInstall": typeof modules_advanced_analytics_onInstall;
  "modules/advanced_analytics/onUninstall": typeof modules_advanced_analytics_onUninstall;
  "modules/advanced_analytics/publicApi": typeof modules_advanced_analytics_publicApi;
  "modules/alumni/configSchema": typeof modules_alumni_configSchema;
  "modules/alumni/eventHandlers": typeof modules_alumni_eventHandlers;
  "modules/alumni/features": typeof modules_alumni_features;
  "modules/alumni/index": typeof modules_alumni_index;
  "modules/alumni/notifications": typeof modules_alumni_notifications;
  "modules/alumni/onInstall": typeof modules_alumni_onInstall;
  "modules/alumni/onUninstall": typeof modules_alumni_onUninstall;
  "modules/alumni/publicApi": typeof modules_alumni_publicApi;
  "modules/attendance/configSchema": typeof modules_attendance_configSchema;
  "modules/attendance/eventHandlers": typeof modules_attendance_eventHandlers;
  "modules/attendance/features": typeof modules_attendance_features;
  "modules/attendance/index": typeof modules_attendance_index;
  "modules/attendance/notifications": typeof modules_attendance_notifications;
  "modules/attendance/onInstall": typeof modules_attendance_onInstall;
  "modules/attendance/onUninstall": typeof modules_attendance_onUninstall;
  "modules/attendance/publicApi": typeof modules_attendance_publicApi;
  "modules/auth/loginAttempts": typeof modules_auth_loginAttempts;
  "modules/auth/passwordHelpers": typeof modules_auth_passwordHelpers;
  "modules/auth/passwordPolicy": typeof modules_auth_passwordPolicy;
  "modules/auth/twoFactorHelpers": typeof modules_auth_twoFactorHelpers;
  "modules/communications/configSchema": typeof modules_communications_configSchema;
  "modules/communications/email": typeof modules_communications_email;
  "modules/communications/emailTemplates": typeof modules_communications_emailTemplates;
  "modules/communications/eventHandlers": typeof modules_communications_eventHandlers;
  "modules/communications/features": typeof modules_communications_features;
  "modules/communications/index": typeof modules_communications_index;
  "modules/communications/mutations": typeof modules_communications_mutations;
  "modules/communications/notifications": typeof modules_communications_notifications;
  "modules/communications/onInstall": typeof modules_communications_onInstall;
  "modules/communications/onUninstall": typeof modules_communications_onUninstall;
  "modules/communications/platform": typeof modules_communications_platform;
  "modules/communications/platformInviteEmails": typeof modules_communications_platformInviteEmails;
  "modules/communications/queries": typeof modules_communications_queries;
  "modules/communications/sms": typeof modules_communications_sms;
  "modules/communications/templates": typeof modules_communications_templates;
  "modules/communications/workos": typeof modules_communications_workos;
  "modules/ecommerce/index": typeof modules_ecommerce_index;
  "modules/ecommerce/mutations": typeof modules_ecommerce_mutations;
  "modules/ecommerce/notifications": typeof modules_ecommerce_notifications;
  "modules/ecommerce/onInstall": typeof modules_ecommerce_onInstall;
  "modules/ecommerce/onUninstall": typeof modules_ecommerce_onUninstall;
  "modules/ecommerce/publicApi": typeof modules_ecommerce_publicApi;
  "modules/ecommerce/queries": typeof modules_ecommerce_queries;
  "modules/ewallet/configSchema": typeof modules_ewallet_configSchema;
  "modules/ewallet/eventHandlers": typeof modules_ewallet_eventHandlers;
  "modules/ewallet/features": typeof modules_ewallet_features;
  "modules/ewallet/index": typeof modules_ewallet_index;
  "modules/ewallet/mutations": typeof modules_ewallet_mutations;
  "modules/ewallet/notifications": typeof modules_ewallet_notifications;
  "modules/ewallet/onInstall": typeof modules_ewallet_onInstall;
  "modules/ewallet/onUninstall": typeof modules_ewallet_onUninstall;
  "modules/ewallet/publicApi": typeof modules_ewallet_publicApi;
  "modules/ewallet/queries": typeof modules_ewallet_queries;
  "modules/finance/actions": typeof modules_finance_actions;
  "modules/finance/configSchema": typeof modules_finance_configSchema;
  "modules/finance/eventHandlers": typeof modules_finance_eventHandlers;
  "modules/finance/features": typeof modules_finance_features;
  "modules/finance/index": typeof modules_finance_index;
  "modules/finance/mutations": typeof modules_finance_mutations;
  "modules/finance/notifications": typeof modules_finance_notifications;
  "modules/finance/onInstall": typeof modules_finance_onInstall;
  "modules/finance/onUninstall": typeof modules_finance_onUninstall;
  "modules/finance/paymentUtils": typeof modules_finance_paymentUtils;
  "modules/finance/publicApi": typeof modules_finance_publicApi;
  "modules/finance/queries": typeof modules_finance_queries;
  "modules/hr/configSchema": typeof modules_hr_configSchema;
  "modules/hr/eventHandlers": typeof modules_hr_eventHandlers;
  "modules/hr/features": typeof modules_hr_features;
  "modules/hr/index": typeof modules_hr_index;
  "modules/hr/mutations": typeof modules_hr_mutations;
  "modules/hr/notifications": typeof modules_hr_notifications;
  "modules/hr/onInstall": typeof modules_hr_onInstall;
  "modules/hr/onUninstall": typeof modules_hr_onUninstall;
  "modules/hr/publicApi": typeof modules_hr_publicApi;
  "modules/hr/queries": typeof modules_hr_queries;
  "modules/library/configSchema": typeof modules_library_configSchema;
  "modules/library/eventHandlers": typeof modules_library_eventHandlers;
  "modules/library/features": typeof modules_library_features;
  "modules/library/index": typeof modules_library_index;
  "modules/library/mutations": typeof modules_library_mutations;
  "modules/library/notifications": typeof modules_library_notifications;
  "modules/library/onInstall": typeof modules_library_onInstall;
  "modules/library/onUninstall": typeof modules_library_onUninstall;
  "modules/library/publicApi": typeof modules_library_publicApi;
  "modules/library/queries": typeof modules_library_queries;
  "modules/marketplace/analytics": typeof modules_marketplace_analytics;
  "modules/marketplace/billing": typeof modules_marketplace_billing;
  "modules/marketplace/flags": typeof modules_marketplace_flags;
  "modules/marketplace/installation": typeof modules_marketplace_installation;
  "modules/marketplace/moduleDefinitions": typeof modules_marketplace_moduleDefinitions;
  "modules/marketplace/modules": typeof modules_marketplace_modules;
  "modules/marketplace/mutations": typeof modules_marketplace_mutations;
  "modules/marketplace/pilotGrants": typeof modules_marketplace_pilotGrants;
  "modules/marketplace/planAudit": typeof modules_marketplace_planAudit;
  "modules/marketplace/platform": typeof modules_marketplace_platform;
  "modules/marketplace/platformDashboard": typeof modules_marketplace_platformDashboard;
  "modules/marketplace/pricing": typeof modules_marketplace_pricing;
  "modules/marketplace/publisherOps": typeof modules_marketplace_publisherOps;
  "modules/marketplace/publishers": typeof modules_marketplace_publishers;
  "modules/marketplace/queries": typeof modules_marketplace_queries;
  "modules/marketplace/reviews": typeof modules_marketplace_reviews;
  "modules/marketplace/seed": typeof modules_marketplace_seed;
  "modules/marketplace/settings": typeof modules_marketplace_settings;
  "modules/marketplace/tierModules": typeof modules_marketplace_tierModules;
  "modules/moduleCatalog": typeof modules_moduleCatalog;
  "modules/modulePublicApis": typeof modules_modulePublicApis;
  "modules/moduleRuntime": typeof modules_moduleRuntime;
  "modules/notes/index": typeof modules_notes_index;
  "modules/notes/mutations": typeof modules_notes_mutations;
  "modules/notes/queries": typeof modules_notes_queries;
  "modules/parent_portal/configSchema": typeof modules_parent_portal_configSchema;
  "modules/parent_portal/eventHandlers": typeof modules_parent_portal_eventHandlers;
  "modules/parent_portal/features": typeof modules_parent_portal_features;
  "modules/parent_portal/index": typeof modules_parent_portal_index;
  "modules/parent_portal/notifications": typeof modules_parent_portal_notifications;
  "modules/parent_portal/onInstall": typeof modules_parent_portal_onInstall;
  "modules/parent_portal/onUninstall": typeof modules_parent_portal_onUninstall;
  "modules/parent_portal/publicApi": typeof modules_parent_portal_publicApi;
  "modules/partner/configSchema": typeof modules_partner_configSchema;
  "modules/partner/eventHandlers": typeof modules_partner_eventHandlers;
  "modules/partner/features": typeof modules_partner_features;
  "modules/partner/index": typeof modules_partner_index;
  "modules/partner/notifications": typeof modules_partner_notifications;
  "modules/partner/onInstall": typeof modules_partner_onInstall;
  "modules/partner/onUninstall": typeof modules_partner_onUninstall;
  "modules/partner/publicApi": typeof modules_partner_publicApi;
  "modules/platform/announcements": typeof modules_platform_announcements;
  "modules/platform/crm": typeof modules_platform_crm;
  "modules/platform/currency": typeof modules_platform_currency;
  "modules/platform/onboarding": typeof modules_platform_onboarding;
  "modules/platform/ops": typeof modules_platform_ops;
  "modules/platform/pilotGrants": typeof modules_platform_pilotGrants;
  "modules/platform/rbac": typeof modules_platform_rbac;
  "modules/platform/subscriptions": typeof modules_platform_subscriptions;
  "modules/platform/support": typeof modules_platform_support;
  "modules/platform/users": typeof modules_platform_users;
  "modules/platform/waitlist": typeof modules_platform_waitlist;
  "modules/pm/deploys": typeof modules_pm_deploys;
  "modules/pm/epics": typeof modules_pm_epics;
  "modules/pm/github": typeof modules_pm_github;
  "modules/pm/index": typeof modules_pm_index;
  "modules/pm/projects": typeof modules_pm_projects;
  "modules/pm/roles": typeof modules_pm_roles;
  "modules/pm/tasks": typeof modules_pm_tasks;
  "modules/pm/timeLogs": typeof modules_pm_timeLogs;
  "modules/pm/workspaces": typeof modules_pm_workspaces;
  "modules/portal/alumni/mutations": typeof modules_portal_alumni_mutations;
  "modules/portal/alumni/queries": typeof modules_portal_alumni_queries;
  "modules/portal/index": typeof modules_portal_index;
  "modules/portal/parent/index": typeof modules_portal_parent_index;
  "modules/portal/parent/mutations": typeof modules_portal_parent_mutations;
  "modules/portal/parent/queries": typeof modules_portal_parent_queries;
  "modules/portal/partner/index": typeof modules_portal_partner_index;
  "modules/portal/partner/mutations": typeof modules_portal_partner_mutations;
  "modules/portal/partner/queries": typeof modules_portal_partner_queries;
  "modules/portal/student/index": typeof modules_portal_student_index;
  "modules/portal/student/mutations": typeof modules_portal_student_mutations;
  "modules/portal/student/queries": typeof modules_portal_student_queries;
  "modules/publisher/index": typeof modules_publisher_index;
  "modules/publisher/internal/crons": typeof modules_publisher_internal_crons;
  "modules/publisher/mutations/analytics": typeof modules_publisher_mutations_analytics;
  "modules/publisher/mutations/applications": typeof modules_publisher_mutations_applications;
  "modules/publisher/mutations/modules": typeof modules_publisher_mutations_modules;
  "modules/publisher/mutations/profile": typeof modules_publisher_mutations_profile;
  "modules/publisher/mutations/support": typeof modules_publisher_mutations_support;
  "modules/reseller/index": typeof modules_reseller_index;
  "modules/reseller/internal/crons": typeof modules_reseller_internal_crons;
  "modules/reseller/mutations/applications": typeof modules_reseller_mutations_applications;
  "modules/reseller/mutations/commissions": typeof modules_reseller_mutations_commissions;
  "modules/reseller/mutations/leads": typeof modules_reseller_mutations_leads;
  "modules/reseller/mutations/marketing": typeof modules_reseller_mutations_marketing;
  "modules/reseller/mutations/profile": typeof modules_reseller_mutations_profile;
  "modules/reseller/queries/customers": typeof modules_reseller_queries_customers;
  "modules/reseller/queries/orders": typeof modules_reseller_queries_orders;
  "modules/reseller/queries/products": typeof modules_reseller_queries_products;
  "modules/reseller/queries/referrals": typeof modules_reseller_queries_referrals;
  "modules/reseller/queries/subdomain": typeof modules_reseller_queries_subdomain;
  "modules/reseller/queries/support": typeof modules_reseller_queries_support;
  "modules/sis/mutations": typeof modules_sis_mutations;
  "modules/sis/queries": typeof modules_sis_queries;
  "modules/sis/studentQueries": typeof modules_sis_studentQueries;
  "modules/tasks/mutations": typeof modules_tasks_mutations;
  "modules/tasks/queries": typeof modules_tasks_queries;
  "modules/timetable/configSchema": typeof modules_timetable_configSchema;
  "modules/timetable/eventHandlers": typeof modules_timetable_eventHandlers;
  "modules/timetable/features": typeof modules_timetable_features;
  "modules/timetable/index": typeof modules_timetable_index;
  "modules/timetable/mutations": typeof modules_timetable_mutations;
  "modules/timetable/notifications": typeof modules_timetable_notifications;
  "modules/timetable/onInstall": typeof modules_timetable_onInstall;
  "modules/timetable/onUninstall": typeof modules_timetable_onUninstall;
  "modules/timetable/publicApi": typeof modules_timetable_publicApi;
  "modules/timetable/queries": typeof modules_timetable_queries;
  "modules/transport/configSchema": typeof modules_transport_configSchema;
  "modules/transport/eventHandlers": typeof modules_transport_eventHandlers;
  "modules/transport/features": typeof modules_transport_features;
  "modules/transport/index": typeof modules_transport_index;
  "modules/transport/mutations": typeof modules_transport_mutations;
  "modules/transport/notifications": typeof modules_transport_notifications;
  "modules/transport/onInstall": typeof modules_transport_onInstall;
  "modules/transport/onUninstall": typeof modules_transport_onUninstall;
  "modules/transport/publicApi": typeof modules_transport_publicApi;
  "modules/transport/queries": typeof modules_transport_queries;
  notifications: typeof notifications;
  organizations: typeof organizations;
  parentOnboarding: typeof parentOnboarding;
  "platform/analytics/index": typeof platform_analytics_index;
  "platform/analytics/mutations": typeof platform_analytics_mutations;
  "platform/analytics/queries": typeof platform_analytics_queries;
  "platform/apiKeys/index": typeof platform_apiKeys_index;
  "platform/apiKeys/mutations": typeof platform_apiKeys_mutations;
  "platform/apiKeys/queries": typeof platform_apiKeys_queries;
  "platform/audit/index": typeof platform_audit_index;
  "platform/audit/queries": typeof platform_audit_queries;
  "platform/automation/index": typeof platform_automation_index;
  "platform/automation/mutations": typeof platform_automation_mutations;
  "platform/automation/queries": typeof platform_automation_queries;
  "platform/billing/index": typeof platform_billing_index;
  "platform/billing/mutations": typeof platform_billing_mutations;
  "platform/billing/queries": typeof platform_billing_queries;
  "platform/changelog/index": typeof platform_changelog_index;
  "platform/changelog/mutations": typeof platform_changelog_mutations;
  "platform/changelog/queries": typeof platform_changelog_queries;
  "platform/communications/index": typeof platform_communications_index;
  "platform/communications/mutations": typeof platform_communications_mutations;
  "platform/communications/queries": typeof platform_communications_queries;
  "platform/crm/index": typeof platform_crm_index;
  "platform/crm/mutations": typeof platform_crm_mutations;
  "platform/crm/proposalMutations": typeof platform_crm_proposalMutations;
  "platform/crm/proposalQueries": typeof platform_crm_proposalQueries;
  "platform/crm/queries": typeof platform_crm_queries;
  "platform/dashboard/index": typeof platform_dashboard_index;
  "platform/dashboard/queries": typeof platform_dashboard_queries;
  "platform/dataExport/index": typeof platform_dataExport_index;
  "platform/dataExport/mutations": typeof platform_dataExport_mutations;
  "platform/dataExport/queries": typeof platform_dataExport_queries;
  "platform/featureFlags/index": typeof platform_featureFlags_index;
  "platform/featureFlags/mutations": typeof platform_featureFlags_mutations;
  "platform/featureFlags/queries": typeof platform_featureFlags_queries;
  "platform/files/index": typeof platform_files_index;
  "platform/files/mutations": typeof platform_files_mutations;
  "platform/files/queries": typeof platform_files_queries;
  "platform/health/index": typeof platform_health_index;
  "platform/health/mutations": typeof platform_health_mutations;
  "platform/health/queries": typeof platform_health_queries;
  "platform/impersonation/index": typeof platform_impersonation_index;
  "platform/impersonation/mutations": typeof platform_impersonation_mutations;
  "platform/impersonation/queries": typeof platform_impersonation_queries;
  "platform/index": typeof platform_index;
  "platform/integration/index": typeof platform_integration_index;
  "platform/integration/mutations": typeof platform_integration_mutations;
  "platform/integration/queries": typeof platform_integration_queries;
  "platform/knowledgeBase/index": typeof platform_knowledgeBase_index;
  "platform/knowledgeBase/mutations": typeof platform_knowledgeBase_mutations;
  "platform/knowledgeBase/queries": typeof platform_knowledgeBase_queries;
  "platform/marketplace/index": typeof platform_marketplace_index;
  "platform/marketplace/mutations": typeof platform_marketplace_mutations;
  "platform/marketplace/payments": typeof platform_marketplace_payments;
  "platform/marketplace/queries": typeof platform_marketplace_queries;
  "platform/notifications/index": typeof platform_notifications_index;
  "platform/notifications/mutations": typeof platform_notifications_mutations;
  "platform/notifications/queries": typeof platform_notifications_queries;
  "platform/onboarding/index": typeof platform_onboarding_index;
  "platform/onboarding/mutations": typeof platform_onboarding_mutations;
  "platform/onboarding/queries": typeof platform_onboarding_queries;
  "platform/operations/index": typeof platform_operations_index;
  "platform/operations/mutations": typeof platform_operations_mutations;
  "platform/operations/queries": typeof platform_operations_queries;
  "platform/resellers/mutations": typeof platform_resellers_mutations;
  "platform/resellers/queries": typeof platform_resellers_queries;
  "platform/roleBuilder/index": typeof platform_roleBuilder_index;
  "platform/roleBuilder/mutations": typeof platform_roleBuilder_mutations;
  "platform/roleBuilder/queries": typeof platform_roleBuilder_queries;
  "platform/scheduledReports/index": typeof platform_scheduledReports_index;
  "platform/scheduledReports/mutations": typeof platform_scheduledReports_mutations;
  "platform/scheduledReports/queries": typeof platform_scheduledReports_queries;
  "platform/security/index": typeof platform_security_index;
  "platform/security/mutations": typeof platform_security_mutations;
  "platform/security/queries": typeof platform_security_queries;
  "platform/settings/index": typeof platform_settings_index;
  "platform/settings/maintenanceCheck": typeof platform_settings_maintenanceCheck;
  "platform/settings/mutations": typeof platform_settings_mutations;
  "platform/settings/queries": typeof platform_settings_queries;
  "platform/sla/index": typeof platform_sla_index;
  "platform/sla/mutations": typeof platform_sla_mutations;
  "platform/sla/queries": typeof platform_sla_queries;
  "platform/staffPerformance/index": typeof platform_staffPerformance_index;
  "platform/staffPerformance/mutations": typeof platform_staffPerformance_mutations;
  "platform/staffPerformance/queries": typeof platform_staffPerformance_queries;
  "platform/support/index": typeof platform_support_index;
  "platform/support/mutations": typeof platform_support_mutations;
  "platform/support/queries": typeof platform_support_queries;
  "platform/tenantSuccess/index": typeof platform_tenantSuccess_index;
  "platform/tenantSuccess/mutations": typeof platform_tenantSuccess_mutations;
  "platform/tenantSuccess/queries": typeof platform_tenantSuccess_queries;
  "platform/tenants/actions": typeof platform_tenants_actions;
  "platform/tenants/emailActions": typeof platform_tenants_emailActions;
  "platform/tenants/index": typeof platform_tenants_index;
  "platform/tenants/mutations": typeof platform_tenants_mutations;
  "platform/tenants/queries": typeof platform_tenants_queries;
  "platform/users/index": typeof platform_users_index;
  "platform/users/mutations": typeof platform_users_mutations;
  "platform/users/queries": typeof platform_users_queries;
  "platform/users/utils": typeof platform_users_utils;
  "platform/webhooks/index": typeof platform_webhooks_index;
  "platform/webhooks/mutations": typeof platform_webhooks_mutations;
  "platform/webhooks/queries": typeof platform_webhooks_queries;
  "platform/whiteLabel/index": typeof platform_whiteLabel_index;
  "platform/whiteLabel/mutations": typeof platform_whiteLabel_mutations;
  "platform/whiteLabel/queries": typeof platform_whiteLabel_queries;
  publicApplications: typeof publicApplications;
  sessions: typeof sessions;
  staffInvites: typeof staffInvites;
  "system/maintenance": typeof system_maintenance;
  tenants: typeof tenants;
  tickets: typeof tickets;
  users: typeof users;
  waitlist: typeof waitlist;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
