import type { NavItem } from "@/lib/routes";
import { usePlatformPermissions } from "@/hooks/usePlatformPermissions";
import {
  LayoutDashboard,
  Building2,
  Plus,
  TrendingUp,
  ClipboardCheck,
  Rocket,
  Users,
  Activity,
  UserPlus,
  Shield,
  BarChart3,
  Store,
  Clipboard,
  Tag,
  Flag,
  Star,
  Gift,
  Code,
  CreditCard,
  Package,
  FileText,
  RefreshCw,
  PieChart,
  Target,
  Handshake,
  FileCheck,
  Megaphone,
  Bell,
  BookOpen,
  Calendar,
  Settings,
  Lock,
  FileSearch,
  Key,
  Zap,
  Kanban,
  UserCheck,
} from "lucide-react";

const PLATFORM_NAV_ITEMS: NavItem[] = [
  {
    label: "Dashboard",
    href: "/platform",
    permission: null,
    icon: LayoutDashboard,
  },
  {
    label: "All Tenants",
    href: "/platform/tenants",
    permission: "tenants.view",
    icon: Building2,
    section: "TENANTS",
  },
  {
    label: "Create Tenant",
    href: "/platform/tenants/create",
    permission: "tenants.create",
    icon: Plus,
    section: "TENANTS",
  },
  {
    label: "Tenant Success",
    href: "/platform/tenant-success",
    permission: "onboarding.view",
    icon: TrendingUp,
    section: "TENANTS",
  },
  {
    label: "Waitlist",
    href: "/platform/waitlist",
    permission: "waitlist.view",
    icon: ClipboardCheck,
    section: "TENANTS",
  },
  {
    label: "Onboarding",
    href: "/platform/onboarding",
    permission: "onboarding.view",
    icon: Rocket,
    section: "TENANTS",
  },
  {
    label: "All Users",
    href: "/platform/users",
    permission: "platform_users.view",
    icon: Users,
    section: "USERS & STAFF",
  },
  {
    label: "Sessions",
    href: "/platform/users/sessions",
    permission: "platform_users.view",
    icon: Shield,
    section: "USERS & STAFF",
  },
  {
    label: "Activity Logs",
    href: "/platform/users/activity",
    permission: "platform_users.view",
    icon: Activity,
    section: "USERS & STAFF",
  },
  {
    label: "Invite Staff",
    href: "/platform/users/invite",
    permission: "platform_users.invite",
    icon: UserPlus,
    section: "USERS & STAFF",
  },
  {
    label: "Roles",
    href: "/platform/users/roles",
    permission: "platform_users.view",
    icon: Shield,
    section: "USERS & STAFF",
  },
  {
    label: "Admin",
    href: "/platform/admin",
    permission: "platform_admin.view",
    icon: Settings,
    section: "ADMIN",
  },
  {
    label: "Impersonation",
    href: "/platform/impersonation",
    permission: "tenants.impersonate",
    icon: UserCheck,
    section: "USERS & STAFF",
  },
  {
    label: "Staff Performance",
    href: "/platform/staff-performance",
    permission: "staff_performance.view",
    icon: BarChart3,
    section: "USERS & STAFF",
  },
  {
    label: "Overview",
    href: "/platform/marketplace",
    permission: "marketplace.view",
    icon: Store,
    section: "MARKETPLACE",
  },
  {
    label: "Review Queue",
    href: "/platform/marketplace/admin",
    permission: "marketplace.review_modules",
    icon: Clipboard,
    section: "MARKETPLACE",
  },
  {
    label: "Pricing",
    href: "/platform/marketplace/pricing",
    permission: "marketplace.manage_pricing",
    icon: Tag,
    section: "MARKETPLACE",
  },
  {
    label: "Flags",
    href: "/platform/marketplace/flags",
    permission: "marketplace.manage_flags",
    icon: Flag,
    section: "MARKETPLACE",
  },
  {
    label: "Reviews",
    href: "/platform/marketplace/reviews",
    permission: "marketplace.manage_reviews",
    icon: Star,
    section: "MARKETPLACE",
  },
  {
    label: "Pilot Grants",
    href: "/platform/marketplace/pilot-grants",
    permission: "marketplace.manage_pilot_grants",
    icon: Gift,
    section: "MARKETPLACE",
  },
  {
    label: "Publishers",
    href: "/platform/marketplace/publishers",
    permission: "publishers.view",
    icon: Code,
    section: "MARKETPLACE",
  },
  {
    label: "Dashboard",
    href: "/platform/billing",
    permission: "billing.view_dashboard",
    icon: CreditCard,
    section: "BILLING",
  },
  {
    label: "Plans",
    href: "/platform/billing/plans",
    permission: "billing.manage_plans",
    icon: Package,
    section: "BILLING",
  },
  {
    label: "Invoices",
    href: "/platform/billing/invoices",
    permission: "billing.view_invoices",
    icon: FileText,
    section: "BILLING",
  },
  {
    label: "Subscriptions",
    href: "/platform/billing/subscriptions",
    permission: "billing.view_subscriptions",
    icon: RefreshCw,
    section: "BILLING",
  },
  {
    label: "Reports",
    href: "/platform/billing/reports",
    permission: "billing.view_reports",
    icon: PieChart,
    section: "BILLING",
  },
  {
    label: "Leads",
    href: "/platform/crm/leads",
    permission: "crm.view",
    icon: Target,
    section: "CRM",
  },
  {
    label: "Deals",
    href: "/platform/crm",
    permission: "crm.view",
    icon: Handshake,
    section: "CRM",
  },
  {
    label: "Proposals",
    href: "/platform/crm/proposals",
    permission: "crm.create_proposal",
    icon: FileCheck,
    section: "CRM",
  },
  {
    label: "Broadcast",
    href: "/platform/communications/broadcast",
    permission: "communications.send_broadcast",
    icon: Megaphone,
    section: "COMMUNICATIONS",
  },
  {
    label: "Announcements",
    href: "/platform/communications",
    permission: "communications.manage_announcements",
    icon: Bell,
    section: "COMMUNICATIONS",
  },
  {
    label: "Knowledge Base",
    href: "/platform/knowledge-base",
    permission: "knowledge_base.view",
    icon: BookOpen,
    section: "COMMUNICATIONS",
  },
  {
    label: "Analytics",
    href: "/platform/analytics",
    permission: "analytics.view_platform",
    icon: BarChart3,
    section: "OPERATIONS",
  },
  {
    label: "Scheduled Reports",
    href: "/platform/scheduled-reports",
    permission: "analytics.manage_reports",
    icon: Calendar,
    section: "OPERATIONS",
  },
  {
    label: "SLA",
    href: "/platform/sla",
    permission: "settings.manage_sla",
    icon: Settings,
    section: "OPERATIONS",
  },
  {
    label: "Resellers",
    href: "/platform/resellers",
    permission: "resellers.view",
    icon: Users,
    section: "OPERATIONS",
  },
  {
    label: "Settings",
    href: "/platform/settings",
    permission: "settings.view",
    icon: Settings,
    section: "SETTINGS & SECURITY",
  },
  {
    label: "Feature Flags",
    href: "/platform/feature-flags",
    permission: "settings.manage_feature_flags",
    icon: Flag,
    section: "SETTINGS & SECURITY",
  },
  {
    label: "Security",
    href: "/platform/security",
    permission: "security.view_dashboard",
    icon: Lock,
    section: "SETTINGS & SECURITY",
  },
  {
    label: "Audit Log",
    href: "/platform/audit",
    permission: "security.view_audit_log",
    icon: FileSearch,
    section: "SETTINGS & SECURITY",
  },
  {
    label: "API Keys",
    href: "/platform/api-keys",
    permission: "security.manage_api_keys",
    icon: Key,
    section: "SETTINGS & SECURITY",
  },
  {
    label: "Webhooks",
    href: "/platform/webhooks",
    permission: "security.manage_webhooks",
    icon: Zap,
    section: "SETTINGS & SECURITY",
  },
  {
    label: "PM",
    href: "/platform/pm",
    permission: "pm.view",
    icon: Kanban,
    section: "PROJECT MANAGEMENT",
  },
];

export function usePermissionBasedNavItems(): NavItem[] {
  const { can, isLoaded } = usePlatformPermissions();

  if (!isLoaded) return [];

  return PLATFORM_NAV_ITEMS.filter(item => 
    !item.permission || can(item.permission)
  );
}

export function getNavItemsBySection(navItems: NavItem[]): Array<{section: string, items: NavItem[]}> {
  const grouped = navItems.reduce((acc, item) => {
    const section = item.section || "__standalone__";
    if (!acc[section]) acc[section] = [];
    acc[section].push(item);
    return acc;
  }, {} as Record<string, NavItem[]>);

  // Convert to array of {section, items} objects
  return Object.entries(grouped).map(([section, items]) => ({
    section,
    items
  }));
}

export function getPermissionTooltip(permission: string): string {
  const permissionMap: Record<string, string> = {
    "tenants.view": "Requires permission to view tenants",
    "tenants.create": "Requires permission to create tenants",
    "tenants.edit": "Requires permission to edit tenants",
    "tenants.suspend": "Requires permission to suspend tenants",
    "tenants.delete": "Requires permission to delete tenants (master admin only)",
    "tenants.impersonate": "Requires permission to impersonate users",
    "tenants.export": "Requires permission to export tenant data",
    "tenants.view_finance": "Requires permission to view financial data",
    "tenants.manage_finance": "Requires permission to manage billing",
    "tenants.manage_subscription": "Requires permission to manage subscriptions",
    "tenants.manage_modules": "Requires permission to manage modules",
    "tenants.manage_users": "Requires permission to manage tenant users",
    "tenants.manage_settings": "Requires permission to manage tenant settings",
    "tenants.manage_pilot_grants": "Requires permission to manage pilot grants",
    "tenants.grant_permanent_free": "Requires permission to grant permanent free access",
    "tenants.set_custom_pricing": "Requires permission to set custom pricing",
    "tenants.gdpr_export": "Requires permission to trigger GDPR export",
    "platform_users.view": "Requires permission to view platform users",
    "platform_users.invite": "Requires permission to invite platform users",
    "platform_users.edit_role": "Requires permission to edit user roles",
    "platform_users.edit_permissions": "Requires permission to edit permission overrides",
    "platform_users.suspend": "Requires permission to suspend platform users",
    "platform_users.delete": "Requires permission to delete platform users (master admin only)",
    "platform_users.view_activity": "Requires permission to view user activity logs",
    "marketplace.view": "Requires permission to view marketplace",
    "marketplace.review_modules": "Requires permission to review modules",
    "marketplace.suspend_module": "Requires permission to suspend modules",
    "marketplace.ban_module": "Requires permission to ban modules (master admin only)",
    "marketplace.feature_module": "Requires permission to feature modules",
    "marketplace.override_price": "Requires permission to override module prices",
    "marketplace.manage_flags": "Requires permission to manage module flags",
    "marketplace.manage_reviews": "Requires permission to manage reviews",
    "marketplace.manage_pilot_grants": "Requires permission to manage pilot grants",
    "marketplace.bulk_pilot_grants": "Requires permission to bulk grant pilot access",
    "marketplace.manage_pricing": "Requires permission to manage pricing",
    "publishers.view": "Requires permission to view publishers",
    "publishers.approve": "Requires permission to approve publishers",
    "publishers.reject": "Requires permission to reject publishers",
    "publishers.suspend": "Requires permission to suspend publishers",
    "publishers.ban": "Requires permission to ban publishers (master admin only)",
    "publishers.manage_revenue_share": "Requires permission to manage revenue share (master admin only)",
    "publishers.manage_tier": "Requires permission to manage publisher tiers",
    "publishers.process_payouts": "Requires permission to process payouts",
    "publishers.view_payouts": "Requires permission to view payout data",
    "billing.view_dashboard": "Requires permission to view billing dashboard",
    "billing.view_invoices": "Requires permission to view invoices",
    "billing.manage_invoices": "Requires permission to manage invoices",
    "billing.view_subscriptions": "Requires permission to view subscriptions",
    "billing.manage_subscriptions": "Requires permission to manage subscriptions",
    "billing.view_reports": "Requires permission to view billing reports",
    "billing.export_reports": "Requires permission to export billing reports",
    "billing.manage_plans": "Requires permission to manage plans (master admin only)",
    "billing.view_publisher_payouts": "Requires permission to view publisher payouts",
    "billing.process_payouts": "Requires permission to process payouts",
    "crm.view": "Requires permission to view CRM",
    "crm.create_lead": "Requires permission to create leads",
    "crm.edit_lead": "Requires permission to edit leads",
    "crm.assign_lead": "Requires permission to assign leads",
    "crm.delete_lead": "Requires permission to delete leads",
    "crm.create_proposal": "Requires permission to create proposals",
    "crm.convert_to_tenant": "Requires permission to convert leads to tenants",
    "communications.view": "Requires permission to view communications",
    "communications.send_broadcast": "Requires permission to send broadcasts",
    "communications.send_sms": "Requires permission to send SMS",
    "communications.manage_templates": "Requires permission to manage templates (master admin only)",
    "communications.view_logs": "Requires permission to view delivery logs",
    "communications.manage_announcements": "Requires permission to manage announcements",
    "knowledge_base.view": "Requires permission to view knowledge base",
    "knowledge_base.create": "Requires permission to create articles",
    "knowledge_base.edit": "Requires permission to edit articles",
    "knowledge_base.publish": "Requires permission to publish articles",
    "knowledge_base.delete": "Requires permission to delete articles (master admin only)",
    "analytics.view_platform": "Requires permission to view platform analytics",
    "analytics.view_business": "Requires permission to view business analytics",
    "analytics.export": "Requires permission to export analytics",
    "analytics.manage_reports": "Requires permission to manage reports",
    "security.view_dashboard": "Requires permission to view security dashboard",
    "security.view_audit_log": "Requires permission to view audit log",
    "security.export_audit_log": "Requires permission to export audit log (master admin only)",
    "security.manage_api_keys": "Requires permission to manage API keys",
    "security.manage_webhooks": "Requires permission to manage webhooks",
    "security.flag_audit_entries": "Requires permission to flag audit entries",
    "settings.view": "Requires permission to view settings",
    "settings.edit_general": "Requires permission to edit general settings",
    "settings.edit_email": "Requires permission to edit email settings",
    "settings.edit_sms": "Requires permission to edit SMS settings",
    "settings.edit_payments": "Requires permission to edit payment settings (master admin only)",
    "settings.edit_security": "Requires permission to edit security settings (master admin only)",
    "settings.edit_integrations": "Requires permission to edit integrations",
    "settings.maintenance_mode": "Requires permission to toggle maintenance mode (master admin only)",
    "settings.manage_feature_flags": "Requires permission to manage feature flags",
    "settings.manage_sla": "Requires permission to manage SLA settings",
    "support.view": "Requires permission to view support tickets",
    "support.assign": "Requires permission to assign tickets",
    "support.reply": "Requires permission to reply to tickets",
    "support.close": "Requires permission to close tickets",
    "support.escalate": "Requires permission to escalate tickets",
    "support.view_internal_notes": "Requires permission to view internal notes",
    "waitlist.view": "Requires permission to view waitlist",
    "waitlist.invite": "Requires permission to invite from waitlist",
    "waitlist.reject": "Requires permission to reject waitlist entries",
    "onboarding.view": "Requires permission to view onboarding",
    "onboarding.manage": "Requires permission to manage onboarding",
    "resellers.view": "Requires permission to view resellers",
    "resellers.approve": "Requires permission to approve resellers",
    "resellers.reject": "Requires permission to reject resellers",
    "resellers.manage_tier": "Requires permission to manage reseller tiers",
    "resellers.manage_commission": "Requires permission to manage commission (master admin only)",
    "resellers.suspend": "Requires permission to suspend resellers",
    "resellers.terminate": "Requires permission to terminate resellers (master admin only)",
    "resellers.process_payouts": "Requires permission to process reseller payouts",
    "resellers.manage_materials": "Requires permission to manage marketing materials",
    "resellers.manage_directory": "Requires permission to manage directory listings",
    "resellers.manage_tiers_config": "Requires permission to manage tier configuration (master admin only)",
    "staff_performance.view": "Requires permission to view staff performance",
    "staff_performance.view_own": "Requires permission to view own performance",
    "staff_performance.add_notes": "Requires permission to add evaluation notes",
    "pm.view": "Requires permission to view project management",
    "pm.create": "Requires permission to create projects",
    "pm.manage": "Requires permission to manage projects",
  };

  return permissionMap[permission] || `Requires permission: ${permission}`;
}
