import { NextRequest, NextResponse } from "next/server";
import { ConvexHttpClient } from "convex/browser";
import { api } from "@/convex/_generated/api";

function getConvex() {
  const url = process.env.NEXT_PUBLIC_CONVEX_URL;
  if (!url) throw new Error("NEXT_PUBLIC_CONVEX_URL not configured");
  return new ConvexHttpClient(url);
}

export async function GET(
  req: NextRequest,
  { params }: { params: { paymentId: string } }
) {
  const sessionToken = req.cookies.get("session_token")?.value;
  if (!sessionToken) {
    return new NextResponse("Unauthorised", { status: 401 });
  }

  const convex = getConvex();
  const data = await convex.query(api.modules.finance.queries.getReceiptData, {
    paymentId: params.paymentId as any,
    sessionToken,
  });

  if (!data) {
    return new NextResponse("Receipt not found", { status: 404 });
  }

  const { payment, invoice, student } = data as any;

  const receiptNumber = payment.receiptNumber ?? `RCP-${payment._id.slice(-8).toUpperCase()}`;
  const studentName = student
    ? `${student.firstName ?? ""} ${student.lastName ?? ""}`.trim()
    : invoice?.studentId ?? "—";
  const paidAt = payment.paidAt
    ? new Date(payment.paidAt).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })
    : new Date(payment.createdAt).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });
  const method = (payment.method ?? "").replace(/_/g, " ").replace(/\b\w/g, (c: string) => c.toUpperCase());
  const amount = Number(payment.amount ?? 0).toLocaleString();
  const currency = payment.currency ?? invoice?.currency ?? "KES";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Receipt ${receiptNumber}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', Arial, sans-serif; font-size: 14px; color: #111; background: #fff; }
    @media print {
      @page { size: A5; margin: 15mm; }
      body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
      .no-print { display: none; }
    }
    .container { max-width: 480px; margin: 40px auto; padding: 32px; border: 1px solid #e5e7eb; border-radius: 8px; }
    .header { text-align: center; border-bottom: 2px solid #0F4C2A; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 22px; font-weight: 700; color: #0F4C2A; }
    .header p { font-size: 12px; color: #6b7280; margin-top: 4px; }
    .badge { display: inline-block; background: #dcfce7; color: #15803d; font-size: 11px; font-weight: 600; padding: 2px 10px; border-radius: 99px; letter-spacing: 0.5px; text-transform: uppercase; }
    .receipt-no { text-align: center; margin-bottom: 20px; }
    .receipt-no span { font-size: 12px; color: #6b7280; }
    .receipt-no strong { font-size: 16px; display: block; margin-top: 4px; color: #111; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    td { padding: 8px 0; font-size: 13px; border-bottom: 1px solid #f3f4f6; }
    td:first-child { color: #6b7280; width: 45%; }
    td:last-child { font-weight: 500; text-align: right; }
    .amount-row td { font-size: 18px; font-weight: 700; color: #0F4C2A; border-bottom: none; padding-top: 16px; }
    .footer { text-align: center; font-size: 11px; color: #9ca3af; margin-top: 24px; border-top: 1px solid #f3f4f6; padding-top: 16px; }
    .print-btn { display: block; margin: 20px auto 0; padding: 10px 28px; background: #0F4C2A; color: #fff; border: none; border-radius: 6px; font-size: 14px; cursor: pointer; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>OFFICIAL RECEIPT</h1>
      <p>EduMyles School Management System</p>
    </div>
    <div class="receipt-no">
      <span>Receipt Number</span>
      <strong>${receiptNumber}</strong>
      <div style="margin-top:8px"><span class="badge">PAID</span></div>
    </div>
    <table>
      <tr><td>Student</td><td>${studentName}</td></tr>
      <tr><td>Invoice #</td><td>${invoice?.invoiceNumber ?? invoice?._id?.slice(-6) ?? "—"}</td></tr>
      <tr><td>Description</td><td>${invoice?.description ?? payment.description ?? "Fee Payment"}</td></tr>
      <tr><td>Payment Method</td><td>${method || "—"}</td></tr>
      <tr><td>Transaction Ref</td><td>${payment.reference ?? payment.externalId ?? "—"}</td></tr>
      <tr><td>Date</td><td>${paidAt}</td></tr>
      <tr class="amount-row"><td>Amount Paid</td><td>${currency} ${amount}</td></tr>
    </table>
    <div class="footer">
      <p>This is an official receipt generated by EduMyles.</p>
      <p>Please retain this document for your records.</p>
    </div>
    <button class="print-btn no-print" onclick="window.print()">Print / Save as PDF</button>
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
