import { internalAction, internalMutation, mutation } from "../../_generated/server";
import { internal } from "../../_generated/api";
import { v } from "convex/values";
import { Id } from "../../_generated/dataModel";
import { requirePlatformSession } from "../../helpers/platformGuard";
import { logAction } from "../../helpers/auditLog";

type ScheduledReportDoc = {
  _id: Id<"scheduledReports">;
  tenantId: string;
  name: string;
  reportType: string;
  schedule: string;
  format: "csv" | "excel" | "pdf";
  recipients: string[];
  filters: Record<string, unknown>;
  createdBy: string;
  isActive: boolean;
  nextRun?: number;
  lastRun?: number;
};

function computeNextRun(schedule: string, from = Date.now()) {
  switch (schedule) {
    case "daily":
      return from + 24 * 60 * 60 * 1000;
    case "weekly":
      return from + 7 * 24 * 60 * 60 * 1000;
    case "monthly":
      return from + 30 * 24 * 60 * 60 * 1000;
    default:
      return from + 24 * 60 * 60 * 1000;
  }
}

function buildReportSummary(report: ScheduledReportDoc, generatedAt: number) {
  const readableType = report.reportType.replaceAll("_", " ");
  return [
    `EduMyles scheduled report`,
    ``,
    `Report: ${report.name}`,
    `Type: ${readableType}`,
    `Format: ${report.format.toUpperCase()}`,
    `Generated: ${new Date(generatedAt).toLocaleString("en-GB", { hour12: false })}`,
    `Schedule: ${report.schedule}`,
    `Filters: ${Object.keys(report.filters ?? {}).length > 0 ? JSON.stringify(report.filters) : "None"}`,
    ``,
    `This automated delivery was generated by the platform scheduled-reports runner.`,
  ].join("\n");
}

export const createScheduledReport = mutation({
  args: {
    sessionToken: v.string(),
    name: v.string(),
    reportType: v.string(),
    schedule: v.string(),
    filters: v.optional(v.record(v.string(), v.any())),
    format: v.union(v.literal("csv"), v.literal("excel"), v.literal("pdf")),
    recipients: v.array(v.string()),
  },
  handler: async (ctx, args) => {
    const { tenantId, userId, email } = await requirePlatformSession(ctx, {
      sessionToken: args.sessionToken,
    });

    const now = Date.now();
    const id = await ctx.db.insert("scheduledReports", {
      name: args.name,
      reportType: args.reportType,
      schedule: args.schedule,
      filters: args.filters ?? {},
      format: args.format,
      recipients: args.recipients,
      nextRun: computeNextRun(args.schedule, now),
      isActive: true,
      createdBy: userId,
      tenantId,
      createdAt: now,
      updatedAt: now,
    });

    await logAction(ctx, {
      tenantId,
      actorId: userId,
      actorEmail: email,
      action: "scheduled_report.created",
      entityType: "scheduled_report",
      entityId: String(id),
      after: { name: args.name, reportType: args.reportType, schedule: args.schedule, format: args.format, recipients: args.recipients },
    });

    return { success: true, id, message: "Scheduled report created" };
  },
});

export const updateScheduledReport = mutation({
  args: {
    sessionToken: v.string(),
    reportId: v.string(),
    name: v.optional(v.string()),
    reportType: v.optional(v.string()),
    schedule: v.optional(v.string()),
    filters: v.optional(v.record(v.string(), v.any())),
    format: v.optional(v.union(v.literal("csv"), v.literal("excel"), v.literal("pdf"))),
    recipients: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    const { tenantId, userId, email } = await requirePlatformSession(ctx, { sessionToken: args.sessionToken });

    const report = await ctx.db.get(args.reportId as Id<"scheduledReports">);
    if (!report) throw new Error("Report not found");

    const updates: Record<string, unknown> = { updatedAt: Date.now() };
    if (args.name !== undefined) updates.name = args.name;
    if (args.reportType !== undefined) updates.reportType = args.reportType;
    if (args.schedule !== undefined) {
      updates.schedule = args.schedule;
      updates.nextRun = computeNextRun(args.schedule);
    }
    if (args.filters !== undefined) updates.filters = args.filters;
    if (args.format !== undefined) updates.format = args.format;
    if (args.recipients !== undefined) updates.recipients = args.recipients;

    await ctx.db.patch(args.reportId as Id<"scheduledReports">, updates);

    await logAction(ctx, {
      tenantId,
      actorId: userId,
      actorEmail: email,
      action: "scheduled_report.updated",
      entityType: "scheduled_report",
      entityId: args.reportId,
      before: { name: report.name, reportType: report.reportType, schedule: report.schedule, format: report.format, recipients: report.recipients },
      after: updates,
    });

    return { success: true, message: "Report updated" };
  },
});

export const deleteScheduledReport = mutation({
  args: {
    sessionToken: v.string(),
    reportId: v.string(),
    reason: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const { tenantId, userId, email } = await requirePlatformSession(ctx, { sessionToken: args.sessionToken });

    const report = await ctx.db.get(args.reportId as Id<"scheduledReports">);
    if (!report) throw new Error("Report not found");

    await ctx.db.delete(args.reportId as Id<"scheduledReports">);

    await logAction(ctx, {
      tenantId,
      actorId: userId,
      actorEmail: email,
      action: "scheduled_report.deleted",
      entityType: "scheduled_report",
      entityId: args.reportId,
      before: {
        name: report.name,
        reportType: report.reportType,
        schedule: report.schedule,
        reason: args.reason?.trim() || null,
      },
    });

    return { success: true, message: "Report deleted" };
  },
});

export const toggleActive = mutation({
  args: {
    sessionToken: v.string(),
    reportId: v.string(),
  },
  handler: async (ctx, args) => {
    await requirePlatformSession(ctx, { sessionToken: args.sessionToken });

    const report = await ctx.db.get(args.reportId as Id<"scheduledReports">);
    if (!report) throw new Error("Report not found");

    const isActive = !report.isActive;
    await ctx.db.patch(args.reportId as Id<"scheduledReports">, {
      isActive,
      nextRun: isActive ? computeNextRun(report.schedule) : undefined,
      updatedAt: Date.now(),
    });

    return { success: true, isActive };
  },
});

export const runNow = mutation({
  args: {
    sessionToken: v.string(),
    reportId: v.string(),
  },
  handler: async (ctx, args) => {
    const { tenantId, userId, email } = await requirePlatformSession(ctx, { sessionToken: args.sessionToken });

    const report = await ctx.db.get(args.reportId as Id<"scheduledReports">);
    if (!report) throw new Error("Report not found");

    const runId = await ctx.db.insert("scheduledReportRuns", {
      reportId: args.reportId,
      status: "running",
      startedAt: Date.now(),
      tenantId,
    });

    await ctx.scheduler.runAfter(0, internal.platform.scheduledReports.mutations.executeScheduledReport, {
      reportId: report._id,
      runId,
      triggeredBy: userId,
      actorEmail: email,
      reason: "manual",
    });

    return { success: true, runId, message: "Report run queued" };
  },
});

export const processDueReports = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();
    const dueReports = await ctx.db
      .query("scheduledReports")
      .withIndex("by_nextRun", (q) => q.lte("nextRun", now))
      .collect();

    for (const report of dueReports.filter((item) => item.isActive)) {
      const runId = await ctx.db.insert("scheduledReportRuns", {
        reportId: report._id,
        status: "running",
        startedAt: now,
        tenantId: report.tenantId,
      });

      await ctx.scheduler.runAfter(0, internal.platform.scheduledReports.mutations.executeScheduledReport, {
        reportId: report._id,
        runId,
        triggeredBy: report.createdBy,
        actorEmail: "scheduler@edumyles.com",
        reason: "scheduled",
      });

      await ctx.db.patch(report._id, {
        nextRun: computeNextRun(report.schedule, now),
        updatedAt: now,
      });
    }
  },
});

export const executeScheduledReport = internalAction({
  args: {
    reportId: v.id("scheduledReports"),
    runId: v.id("scheduledReportRuns"),
    triggeredBy: v.string(),
    actorEmail: v.string(),
    reason: v.string(),
  },
  handler: async (ctx, args) => {
    const report = await ctx.runQuery(internal.platform.scheduledReports.queries.getScheduledReportInternal, {
      reportId: args.reportId,
    });

    if (!report) {
      await ctx.runMutation(internal.platform.scheduledReports.mutations.finalizeScheduledReportRun, {
        reportId: args.reportId,
        runId: args.runId,
        status: "failed",
        completedAt: Date.now(),
        error: "Scheduled report no longer exists.",
      });
      return;
    }

    const generatedAt = Date.now();
    const summary = buildReportSummary(report as ScheduledReportDoc, generatedAt);

    try {
      await ctx.runAction(internal.actions.communications.email.sendEmailInternal, {
        tenantId: report.tenantId,
        actorId: args.triggeredBy,
        actorEmail: args.actorEmail,
        to: report.recipients,
        subject: `[EduMyles Report] ${report.name}`,
        text: summary,
      });

      await ctx.runMutation(internal.platform.scheduledReports.mutations.finalizeScheduledReportRun, {
        reportId: args.reportId,
        runId: args.runId,
        status: "completed",
        completedAt: Date.now(),
        resultUrl: `/platform/scheduled-reports?report=${args.reportId}&run=${args.runId}`,
      });
    } catch (error) {
      await ctx.runMutation(internal.platform.scheduledReports.mutations.finalizeScheduledReportRun, {
        reportId: args.reportId,
        runId: args.runId,
        status: "failed",
        completedAt: Date.now(),
        error: error instanceof Error ? error.message : "Scheduled report delivery failed.",
      });
    }
  },
});

export const finalizeScheduledReportRun = internalMutation({
  args: {
    reportId: v.id("scheduledReports"),
    runId: v.id("scheduledReportRuns"),
    status: v.union(v.literal("completed"), v.literal("failed")),
    completedAt: v.number(),
    resultUrl: v.optional(v.string()),
    error: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const report = await ctx.db.get(args.reportId);
    await ctx.db.patch(args.runId, {
      status: args.status,
      completedAt: args.completedAt,
      resultUrl: args.resultUrl,
      error: args.error,
    });

    if (report) {
      await ctx.db.patch(args.reportId, {
        lastRun: args.completedAt,
        updatedAt: args.completedAt,
      });
    }
  },
});
