import { query } from "../../_generated/server";
import { v } from "convex/values";

export const getAISupportTickets = query({
  args: {
    sessionToken: v.string(),
    tenantId: v.optional(v.string()),
    status: v.optional(v.union(v.literal("open"), v.literal("in_progress"), v.literal("resolved"), v.literal("closed"), v.literal("escalated"))),
    category: v.optional(v.union(
      v.literal("technical"),
      v.literal("billing"),
      v.literal("account"),
      v.literal("feature_request"),
      v.literal("bug_report"),
      v.literal("general")
    )),
    priority: v.optional(v.union(v.literal("low"), v.literal("medium"), v.literal("high"), v.literal("urgent"))),
    assignedTo: v.optional(v.string()),
    dateRange: v.optional(v.object({
      startDate: v.number(),
      endDate: v.number(),
    })),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    // TODO: Implement AI support tickets retrieval
    return [
      {
        _id: "ticket_1",
        ticketId: "TKT-2024-001",
        title: "Login issues with mobile app",
        description: "Users are experiencing login problems when trying to access the platform through the mobile application. The app shows an error message 'Invalid credentials' even with correct login details.",
        category: "technical",
        priority: "high",
        status: "in_progress",
        tenantId: "tenant_1",
        tenantName: "Nairobi Academy",
        userId: "user_123",
        userName: "John Doe",
        userEmail: "john.doe@nairobiacademy.edu",
        contactInfo: {
          email: "john.doe@nairobiacademy.edu",
          phone: "+254 712 345 678",
        },
        submittedBy: "john.doe@nairobiacademy.edu",
        assignedTo: "agent_1",
        assignedAgentName: "Sarah Chen",
        createdAt: Date.now() - 2 * 60 * 60 * 1000,
        updatedAt: Date.now() - 30 * 60 * 1000,
        resolvedAt: null,
        aiAnalysis: {
          sentiment: {
            score: -0.3,
            label: "negative",
            confidence: 0.85,
            emotions: ["frustrated", "confused"],
            keyPhrases: ["login problems", "invalid credentials", "mobile app"],
          },
          category: {
            predicted: "technical",
            confidence: 0.92,
            reasoning: "Keywords indicate technical authentication issues",
            alternatives: ["technical", "account"],
          },
          priority: {
            predicted: "high",
            confidence: 0.78,
            factors: ["user_impact", "urgency_indicators", "multiple_users_affected"],
            reasoning: "Affects multiple users and core functionality",
          },
          escalation: {
            recommended: false,
            confidence: 0.65,
            reason: "Standard technical issue within support scope",
            suggestedLevel: "level_1",
          },
        },
        aiResponses: [
          {
            _id: "response_1",
            type: "initial",
            content: "Thank you for reporting this issue. I understand you're experiencing login problems with the mobile app. Let me help you troubleshoot this.",
            tone: "empathetic",
            confidence: 0.92,
            generatedAt: Date.now() - 2 * 60 * 60 * 1000,
            generatedBy: "ai_system",
            suggestedActions: [
              "Try clearing the mobile app cache",
              "Ensure you're using the latest app version",
              "Check if the issue occurs on different devices",
            ],
          },
          {
            _id: "response_2",
            type: "follow_up",
            content: "Based on our analysis, this appears to be related to a recent authentication update. Our team is working on a fix and will deploy it shortly.",
            tone: "professional",
            confidence: 0.88,
            generatedAt: Date.now() - 90 * 60 * 1000,
            generatedBy: "ai_system",
            suggestedActions: [
              "Monitor for authentication service updates",
              "Test with different user accounts",
              "Document affected user accounts",
            ],
          },
        ],
        attachments: ["screenshot_1.png", "error_log.txt"],
        tags: ["mobile", "login", "authentication", "urgent"],
        satisfaction: null,
        resolutionTime: null,
        escalationHistory: [],
        knowledgeBaseReferences: ["kb_123", "kb_456"],
      },
      {
        _id: "ticket_2",
        ticketId: "TKT-2024-002",
        title: "Billing inquiry about subscription renewal",
        description: "Customer wants to understand the subscription renewal process and pricing for the upcoming year. They have questions about payment methods and possible discounts.",
        category: "billing",
        priority: "medium",
        status: "resolved",
        tenantId: "tenant_2",
        tenantName: "Mombasa International School",
        userId: "user_456",
        userName: "Jane Smith",
        userEmail: "jane.smith@mombasainternational.edu",
        contactInfo: {
          email: "jane.smith@mombasainternational.edu",
        },
        submittedBy: "jane.smith@mombasainternational.edu",
        assignedTo: "agent_2",
        assignedAgentName: "John Smith",
        createdAt: Date.now() - 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 18 * 60 * 60 * 1000,
        resolvedAt: Date.now() - 18 * 60 * 60 * 1000,
        aiAnalysis: {
          sentiment: {
            score: 0.2,
            label: "neutral",
            confidence: 0.76,
            emotions: ["inquisitive", "neutral"],
            keyPhrases: ["subscription renewal", "pricing", "payment methods", "discounts"],
          },
          category: {
            predicted: "billing",
            confidence: 0.94,
            reasoning: "Clear billing-related keywords and context",
            alternatives: ["billing"],
          },
          priority: {
            predicted: "medium",
            confidence: 0.82,
            factors: ["business_criticality", "timing", "revenue_impact"],
            reasoning: "Important for revenue but not urgent",
          },
          escalation: {
            recommended: false,
            confidence: 0.91,
            reason: "Standard billing inquiry within support scope",
            suggestedLevel: "level_1",
          },
        },
        aiResponses: [
          {
            _id: "response_3",
            type: "initial",
            content: "I'd be happy to help you with your subscription renewal questions. Let me provide you with detailed information about our renewal process and pricing options.",
            tone: "friendly",
            confidence: 0.89,
            generatedAt: Date.now() - 23 * 60 * 60 * 1000,
            generatedBy: "ai_system",
            suggestedActions: [
              "Review current subscription details",
              "Check available discount programs",
              "Prepare renewal timeline",
            ],
          },
          {
            _id: "response_4",
            type: "resolution",
            content: "I've provided you with all the information about subscription renewal, including pricing options and available discounts. Is there anything specific about the renewal process you'd like me to clarify?",
            tone: "professional",
            confidence: 0.85,
            generatedAt: Date.now() - 19 * 60 * 60 * 1000,
            generatedBy: "ai_system",
            suggestedActions: [
              "Confirm understanding of renewal process",
              "Follow up on discount eligibility",
              "Schedule renewal reminder if needed",
            ],
          },
        ],
        attachments: [],
        tags: ["billing", "subscription", "renewal", "pricing"],
        satisfaction: 4.8,
        resolutionTime: 6 * 60 * 60 * 1000,
        escalationHistory: [],
        knowledgeBaseReferences: ["kb_789", "kb_012"],
      },
      {
        _id: "ticket_3",
        ticketId: "TKT-2024-003",
        title: "Feature request for bulk user import",
        description: "School administration team would like the ability to import multiple users at once instead of adding them individually. This would save significant time during student enrollment periods.",
        category: "feature_request",
        priority: "medium",
        status: "escalated",
        tenantId: "tenant_3",
        tenantName: "Kisumu High School",
        userId: "user_789",
        userName: "Michael Johnson",
        userEmail: "michael.johnson@kisumuhigh.edu",
        contactInfo: {
          email: "michael.johnson@kisumuhigh.edu",
          phone: "+254 734 567 890",
        },
        submittedBy: "michael.johnson@kisumuhigh.edu",
        assignedTo: "agent_3",
        assignedAgentName: "Emily Davis",
        createdAt: Date.now() - 12 * 60 * 60 * 1000,
        updatedAt: Date.now() - 6 * 60 * 60 * 1000,
        resolvedAt: null,
        aiAnalysis: {
          sentiment: {
            score: 0.6,
            label: "positive",
            confidence: 0.81,
            emotions: ["enthusiastic", "constructive"],
            keyPhrases: ["bulk import", "save time", "student enrollment", "feature request"],
          },
          category: {
            predicted: "feature_request",
            confidence: 0.88,
            reasoning: "Clear feature enhancement request with specific use case",
            alternatives: ["feature_request", "technical"],
          },
          priority: {
            predicted: "medium",
            confidence: 0.74,
            factors: ["user_impact", "efficiency_gain", "strategic_value"],
            reasoning: "Would significantly improve workflow for multiple users",
          },
          escalation: {
            recommended: true,
            confidence: 0.79,
            reason: "Feature request requires product team evaluation",
            suggestedLevel: "level_2",
          },
        },
        aiResponses: [
          {
            _id: "response_5",
            type: "initial",
            content: "Thank you for your feature request! Bulk user import would indeed be very valuable for schools during enrollment periods. Let me analyze this request and escalate it to our product team.",
            tone: "friendly",
            confidence: 0.86,
            generatedAt: Date.now() - 11 * 60 * 60 * 1000,
            generatedBy: "ai_system",
            suggestedActions: [
              "Document specific requirements",
              "Research existing bulk import solutions",
              "Prepare use case analysis",
            ],
          },
        ],
        attachments: ["import_template.xlsx"],
        tags: ["feature_request", "bulk_import", "user_management", "efficiency"],
        satisfaction: null,
        resolutionTime: null,
        escalationHistory: [
          {
            escalatedAt: Date.now() - 8 * 60 * 60 * 1000,
            escalatedTo: "product_team",
            escalatedBy: "agent_3",
            reason: "Feature request requires product evaluation",
            level: "level_2",
          },
        ],
        knowledgeBaseReferences: ["kb_345"],
      },
    ];
  },
});

export const getAIInsights = query({
  args: {
    sessionToken: v.string(),
    insightType: v.union(v.literal("ticketTrends"), v.literal("agentPerformance"), v.literal("customerSatisfaction"), v.literal("aiEffectiveness")),
    dateRange: v.object({
      startDate: v.number(),
      endDate: v.number(),
    }),
    filters: v.optional(v.record(v.string(), v.any())),
  },
  handler: async (ctx, args) => {
    // TODO: Implement AI insights retrieval
    const insights = {
      ticketTrends: {
        totalTickets: 1247,
        resolvedTickets: 1089,
        averageResolutionTime: 4.2,
        topCategories: ["technical", "billing", "account"],
        trends: [
          { date: "2024-04-01", tickets: 45, resolved: 42, aiHandled: 18 },
          { date: "2024-04-02", tickets: 52, resolved: 48, aiHandled: 22 },
          { date: "2024-04-03", tickets: 38, resolved: 35, aiHandled: 15 },
          { date: "2024-04-04", tickets: 61, resolved: 56, aiHandled: 28 },
          { date: "2024-04-05", tickets: 47, resolved: 44, aiHandled: 21 },
        ],
        aiPerformance: {
          aiHandledTickets: 523,
          aiResolutionRate: 0.68,
          averageResponseTime: 0.5,
          customerSatisfaction: 4.1,
          escalationRate: 0.32,
        },
        recommendations: [
          "Increase AI training data for better accuracy",
          "Implement proactive AI outreach for common issues",
          "Fine-tune sentiment analysis models",
          "Optimize AI response templates for better satisfaction",
        ],
      },
      agentPerformance: {
        totalAgents: 12,
        averageTicketsPerAgent: 104,
        averageResponseTime: 1.8,
        satisfactionScore: 4.6,
        topPerformers: [
          {
            agentId: "agent_1",
            name: "Sarah Chen",
            tickets: 156,
            satisfaction: 4.8,
            averageResponseTime: 1.2,
            aiAssistedTickets: 89,
          },
          {
            agentId: "agent_2",
            name: "John Smith",
            tickets: 142,
            satisfaction: 4.7,
            averageResponseTime: 1.5,
            aiAssistedTickets: 76,
          },
        ],
        recommendations: [
          "Recognize top performers with bonuses",
          "Provide additional training for underperforming agents",
          "Optimize ticket distribution algorithms",
          "Increase AI assistance for routine inquiries",
        ],
      },
      customerSatisfaction: {
        averageRating: 4.3,
        responseRate: 0.87,
        netPromoterScore: 42,
        feedback: [
          "Great support team, very helpful",
          "Quick resolution to my issue",
          "Could improve response time during peak hours",
          "AI responses are helpful but sometimes lack context",
        ],
        recommendations: [
          "Implement 24/7 chat support",
          "Add self-service options for common issues",
          "Improve first-contact resolution rate",
          "Enhance AI context awareness",
        ],
      },
      aiEffectiveness: {
        aiHandledTickets: 523,
        aiResolutionRate: 0.68,
        averageResponseTime: 0.5,
        customerSatisfaction: 4.1,
        escalationRate: 0.32,
        costSavings: 15670.50,
        timeSavings: 234.5,
        recommendations: [
          "Expand AI training data for better accuracy",
          "Implement proactive AI outreach",
          "Fine-tune sentiment analysis models",
          "Add multilingual support for AI responses",
        ],
      },
    };
    
    return insights[args.insightType];
  },
});

export const getAIKnowledgeBase = query({
  args: {
    sessionToken: v.string(),
    category: v.optional(v.union(
      v.literal("troubleshooting"),
      v.literal("how_to"),
      v.literal("faq"),
      v.literal("technical"),
      v.literal("billing"),
      v.literal("account")
    )),
    tags: v.optional(v.array(v.string())),
    keywords: v.optional(v.string()),
    isPublic: v.optional(v.boolean()),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    // TODO: Implement AI knowledge base retrieval
    return [
      {
        _id: "kb_1",
        title: "How to reset your password",
        content: "Follow these steps to reset your password: 1. Click on 'Forgot Password' on the login page. 2. Enter your email address. 3. Check your email for the reset link. 4. Click the link and create a new password. 5. Log in with your new password.",
        category: "troubleshooting",
        tags: ["password", "reset", "login", "security"],
        keywords: ["password", "reset", "forgot", "login", "security"],
        priority: "high",
        isPublic: true,
        viewCount: 1247,
        helpfulCount: 1189,
        createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
        relatedTickets: ["ticket_456", "ticket_789", "ticket_234"],
        aiGenerated: true,
        aiConfidence: 0.94,
        language: "en",
        estimatedReadTime: 2,
      },
      {
        _id: "kb_2",
        title: "Understanding subscription pricing tiers",
        content: "Our platform offers three pricing tiers: 1. Basic - Perfect for small schools ($99/month). 2. Professional - Ideal for growing institutions ($299/month). 3. Enterprise - Custom pricing for large districts. Each tier includes different features and support levels.",
        category: "billing",
        tags: ["pricing", "subscription", "tiers", "billing"],
        keywords: ["pricing", "subscription", "tiers", "billing", "cost"],
        priority: "medium",
        isPublic: true,
        viewCount: 892,
        helpfulCount: 845,
        createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
        relatedTickets: ["ticket_123", "ticket_567"],
        aiGenerated: true,
        aiConfidence: 0.89,
        language: "en",
        estimatedReadTime: 3,
      },
      {
        _id: "kb_3",
        title: "Mobile app troubleshooting guide",
        content: "Common mobile app issues and solutions: 1. App crashes - Clear cache and restart. 2. Login issues - Check network connection and app version. 3. Sync problems - Ensure stable internet and try manual sync. 4. Performance issues - Close other apps and restart device.",
        category: "technical",
        tags: ["mobile", "app", "troubleshooting", "technical"],
        keywords: ["mobile", "app", "crash", "login", "sync", "performance"],
        priority: "high",
        isPublic: true,
        viewCount: 1567,
        helpfulCount: 1432,
        createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
        relatedTickets: ["ticket_001", "ticket_890", "ticket_345"],
        aiGenerated: true,
        aiConfidence: 0.91,
        language: "en",
        estimatedReadTime: 4,
      },
      {
        _id: "kb_4",
        title: "Setting up multi-factor authentication",
        content: "Enable MFA for enhanced security: 1. Go to Account Settings. 2. Click on Security tab. 3. Enable Two-Factor Authentication. 4. Scan QR code with authenticator app. 5. Enter verification code. 6. Save backup codes securely.",
        category: "account",
        tags: ["mfa", "2fa", "security", "authentication"],
        keywords: ["mfa", "2fa", "security", "authentication", "two-factor"],
        priority: "high",
        isPublic: true,
        viewCount: 678,
        helpfulCount: 623,
        createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
        relatedTickets: ["ticket_234", "ticket_567"],
        aiGenerated: true,
        aiConfidence: 0.87,
        language: "en",
        estimatedReadTime: 3,
      },
      {
        _id: "kb_5",
        title: "Frequently asked questions about features",
        content: "Common questions: Q: Can I export data? A: Yes, from the Data Export section. Q: Is there a mobile app? A: Yes, available for iOS and Android. Q: How do I add users? A: Through the User Management section. Q: Can I customize the dashboard? A: Yes, with the customization options.",
        category: "faq",
        tags: ["faq", "questions", "features", "common"],
        keywords: ["export", "mobile", "users", "dashboard", "customize"],
        priority: "medium",
        isPublic: true,
        viewCount: 2341,
        helpfulCount: 2156,
        createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
        updatedAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
        relatedTickets: ["ticket_345", "ticket_678", "ticket_901"],
        aiGenerated: true,
        aiConfidence: 0.85,
        language: "en",
        estimatedReadTime: 5,
      },
    ];
  },
});

export const getAIAgentMetrics = query({
  args: {
    sessionToken: v.string(),
    agentId: v.optional(v.string()),
    dateRange: v.object({
      startDate: v.number(),
      endDate: v.number(),
    }),
    metrics: v.optional(v.array(v.union(
      v.literal("response_time"),
      v.literal("resolution_rate"),
      v.literal("satisfaction"),
      v.literal("tickets_handled"),
      v.literal("ai_assistance")
    )),
  },
  handler: async (ctx, args) => {
    // TODO: Implement AI agent metrics retrieval
    return [
      {
        agentId: "agent_1",
        agentName: "Sarah Chen",
        email: "sarah.chen@edumyles.com",
        role: "Senior Support Agent",
        department: "Technical Support",
        hireDate: Date.now() - 365 * 24 * 60 * 60 * 1000,
        status: "active",
        metrics: {
          totalTickets: 156,
          resolvedTickets: 142,
          averageResponseTime: 1.2,
          averageResolutionTime: 3.8,
          satisfactionScore: 4.8,
          aiAssistedTickets: 89,
          aiResolutionRate: 0.71,
          escalationRate: 0.12,
          firstContactResolution: 0.68,
          customerRetention: 0.94,
        },
        skills: ["technical", "customer_service", "ai_tools", "escalation_handling"],
        certifications: ["Support Professional", "AI Tools Certified"],
        performance: {
          currentMonth: {
            tickets: 28,
            resolved: 26,
            satisfaction: 4.9,
            aiAssisted: 16,
          },
          previousMonth: {
            tickets: 32,
            resolved: 29,
            satisfaction: 4.7,
            aiAssisted: 18,
          },
          trend: "improving",
        },
        training: [
          {
            title: "Advanced AI Support Tools",
            completedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
            score: 92,
          },
          {
            title: "Customer Service Excellence",
            completedAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
            score: 88,
          },
        ],
      },
      {
        agentId: "agent_2",
        agentName: "John Smith",
        email: "john.smith@edumyles.com",
        role: "Support Agent",
        department: "Customer Success",
        hireDate: Date.now() - 180 * 24 * 60 * 60 * 1000,
        status: "active",
        metrics: {
          totalTickets: 142,
          resolvedTickets: 128,
          averageResponseTime: 1.5,
          averageResolutionTime: 4.2,
          satisfactionScore: 4.7,
          aiAssistedTickets: 76,
          aiResolutionRate: 0.65,
          escalationRate: 0.18,
          firstContactResolution: 0.62,
          customerRetention: 0.91,
        },
        skills: ["billing", "account_management", "ai_tools", "customer_success"],
        certifications: ["Customer Success Professional"],
        performance: {
          currentMonth: {
            tickets: 24,
            resolved: 22,
            satisfaction: 4.8,
            aiAssisted: 14,
          },
          previousMonth: {
            tickets: 26,
            resolved: 23,
            satisfaction: 4.6,
            aiAssisted: 15,
          },
          trend: "stable",
        },
        training: [
          {
            title: "AI Support Fundamentals",
            completedAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
            score: 85,
          },
          {
            title: "Billing Systems Training",
            completedAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
            score: 90,
          },
        ],
      },
      {
        agentId: "agent_3",
        agentName: "Emily Davis",
        email: "emily.davis@edumyles.com",
        role: "Support Agent",
        department: "General Support",
        hireDate: Date.now() - 90 * 24 * 60 * 60 * 1000,
        status: "active",
        metrics: {
          totalTickets: 98,
          resolvedTickets: 85,
          averageResponseTime: 2.1,
          averageResolutionTime: 5.6,
          satisfactionScore: 4.5,
          aiAssistedTickets: 52,
          aiResolutionRate: 0.58,
          escalationRate: 0.25,
          firstContactResolution: 0.55,
          customerRetention: 0.87,
        },
        skills: ["general_support", "ai_tools", "communication"],
        certifications: ["Support Professional"],
        performance: {
          currentMonth: {
            tickets: 18,
            resolved: 15,
            satisfaction: 4.6,
            aiAssisted: 10,
          },
          previousMonth: {
            tickets: 20,
            resolved: 17,
            satisfaction: 4.4,
            aiAssisted: 11,
          },
          trend: "improving",
        },
        training: [
          {
            title: "AI Tools Introduction",
            completedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
            score: 82,
          },
        ],
      },
    ];
  },
});

export const getAISystemPerformance = query({
  args: {
    sessionToken: v.string(),
    timeRange: v.union(v.literal("1h"), v.literal("24h"), v.literal("7d"), v.literal("30d")),
    metrics: v.optional(v.array(v.union(
      v.literal("response_time"),
      v.literal("accuracy"),
      v.literal("throughput"),
      v.literal("satisfaction"),
      v.literal("cost_efficiency")
    )),
  },
  handler: async (ctx, args) => {
    // TODO: Implement AI system performance retrieval
    return {
      overview: {
        totalAIRequests: 5234,
        successfulResponses: 4892,
        averageResponseTime: 0.5,
        accuracy: 0.87,
        customerSatisfaction: 4.1,
        costPerResponse: 2.34,
        humanAgentEquivalents: 3.2,
      },
      performance: {
        responseTime: [
          { timestamp: Date.now() - 60 * 60 * 1000, value: 0.45 },
          { timestamp: Date.now() - 50 * 60 * 1000, value: 0.52 },
          { timestamp: Date.now() - 40 * 60 * 1000, value: 0.48 },
          { timestamp: Date.now() - 30 * 60 * 1000, value: 0.51 },
          { timestamp: Date.now() - 20 * 60 * 1000, value: 0.49 },
          { timestamp: Date.now() - 10 * 60 * 1000, value: 0.47 },
        ],
        accuracy: [
          { timestamp: Date.now() - 60 * 60 * 1000, value: 0.85 },
          { timestamp: Date.now() - 50 * 60 * 1000, value: 0.88 },
          { timestamp: Date.now() - 40 * 60 * 1000, value: 0.86 },
          { timestamp: Date.now() - 30 * 60 * 1000, value: 0.89 },
          { timestamp: Date.now() - 20 * 60 * 1000, value: 0.87 },
          { timestamp: Date.now() - 10 * 60 * 1000, value: 0.90 },
        ],
        throughput: [
          { timestamp: Date.now() - 60 * 60 * 1000, value: 45 },
          { timestamp: Date.now() - 50 * 60 * 1000, value: 52 },
          { timestamp: Date.now() - 40 * 60 * 1000, value: 38 },
          { timestamp: Date.now() - 30 * 60 * 1000, value: 61 },
          { timestamp: Date.now() - 20 * 60 * 1000, value: 47 },
          { timestamp: Date.now() - 10 * 60 * 1000, value: 54 },
        ],
        satisfaction: [
          { timestamp: Date.now() - 60 * 60 * 1000, value: 4.0 },
          { timestamp: Date.now() - 50 * 60 * 1000, value: 4.2 },
          { timestamp: Date.now() - 40 * 60 * 1000, value: 4.1 },
          { timestamp: Date.now() - 30 * 60 * 1000, value: 4.3 },
          { timestamp: Date.now() - 20 * 60 * 1000, value: 4.0 },
          { timestamp: Date.now() - 10 * 60 * 1000, value: 4.2 },
        ],
      },
      models: {
        sentimentAnalysis: {
          accuracy: 0.91,
          confidence: 0.87,
          trainingDataSize: 12500,
          lastUpdated: Date.now() - 7 * 24 * 60 * 60 * 1000,
        },
        classification: {
          accuracy: 0.94,
          confidence: 0.89,
          trainingDataSize: 8900,
          lastUpdated: Date.now() - 14 * 24 * 60 * 60 * 1000,
        },
        responseGeneration: {
          accuracy: 0.86,
          confidence: 0.82,
          trainingDataSize: 15600,
          lastUpdated: Date.now() - 3 * 24 * 60 * 60 * 1000,
        },
        escalation: {
          accuracy: 0.88,
          confidence: 0.84,
          trainingDataSize: 6700,
          lastUpdated: Date.now() - 10 * 24 * 60 * 60 * 1000,
        },
      },
      costAnalysis: {
        totalCost: 12250.75,
        costPerTicket: 2.34,
        humanAgentCost: 8.90,
        savings: 15670.50,
        roi: 4.2,
        monthlyTrend: [
          { month: "2024-01", cost: 11890.50, savings: 14523.25 },
          { month: "2024-02", cost: 12345.75, savings: 15890.50 },
          { month: "2024-03", cost: 12515.00, savings: 16234.75 },
          { month: "2024-04", cost: 12250.75, savings: 15670.50 },
        ],
      },
      recommendations: [
        "Fine-tune sentiment model with recent data",
        "Expand training data for response generation",
        "Implement multilingual support",
        "Add proactive AI outreach capabilities",
      ],
    };
  },
});
