export type FallbackMarketplaceModule = {
  moduleId: string;
  name: string;
  shortDescription: string;
  fullDescription: string;
  category: string;
  publisherName: string;
  pricingModel: string;
  priceCents: number;
  currency: string;
  totalInstalls: number;
  totalReviews: number;
  averageRating: number;
  isFeatured: boolean;
  isVerified: boolean;
  isSecurityReviewed: boolean;
  isGdprCompliant: boolean;
  compatiblePlans: string[];
  tags: string[];
  publishedAt: number;
};

const now = Date.now();

export const FALLBACK_MARKETPLACE_MODULES: FallbackMarketplaceModule[] = [
  {
    moduleId: "sis",
    name: "Student Information System",
    shortDescription: "Core student management, enrollment, records, and class administration.",
    fullDescription: "Core student management, enrollment, records, and class administration.",
    category: "administration",
    publisherName: "EduMyles",
    pricingModel: "free",
    priceCents: 0,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: true,
    isVerified: true,
    isSecurityReviewed: true,
    isGdprCompliant: false,
    compatiblePlans: ["free", "starter", "standard", "growth", "pro", "enterprise"],
    tags: ["enrollment", "records", "classes"],
    publishedAt: now,
  },
  {
    moduleId: "communications",
    name: "Communications",
    shortDescription: "Announcements, email, SMS, push notifications, and audience targeting.",
    fullDescription: "Announcements, email, SMS, push notifications, and audience targeting.",
    category: "communication",
    publisherName: "EduMyles",
    pricingModel: "free",
    priceCents: 0,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: true,
    isVerified: true,
    isSecurityReviewed: true,
    isGdprCompliant: false,
    compatiblePlans: ["free", "starter", "standard", "growth", "pro", "enterprise"],
    tags: ["email", "sms", "notifications"],
    publishedAt: now,
  },
  {
    moduleId: "users",
    name: "User Management",
    shortDescription: "Invite users, manage roles, and control access across the institution.",
    fullDescription: "Invite users, manage roles, and control access across the institution.",
    category: "administration",
    publisherName: "EduMyles",
    pricingModel: "free",
    priceCents: 0,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: true,
    isVerified: true,
    isSecurityReviewed: true,
    isGdprCompliant: false,
    compatiblePlans: ["free", "starter", "standard", "growth", "pro", "enterprise"],
    tags: ["users", "roles", "permissions"],
    publishedAt: now,
  },
  {
    moduleId: "admissions",
    name: "Admissions",
    shortDescription: "Manage applications, reviews, enrollment decisions, and onboarding workflows.",
    fullDescription: "Manage applications, reviews, enrollment decisions, and onboarding workflows.",
    category: "administration",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 1500,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["starter", "standard", "growth", "pro", "enterprise"],
    tags: ["applications", "enrollment", "workflow"],
    publishedAt: now,
  },
  {
    moduleId: "academics",
    name: "Academics",
    shortDescription: "Grades, exams, subjects, curriculum management, and performance tracking.",
    fullDescription: "Grades, exams, subjects, curriculum management, and performance tracking.",
    category: "academic_tools",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 2000,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["standard", "growth", "pro", "enterprise"],
    tags: ["grades", "exams", "curriculum"],
    publishedAt: now,
  },
  {
    moduleId: "finance",
    name: "Finance & Fees",
    shortDescription: "Fee structures, invoicing, payment tracking, and financial reporting.",
    fullDescription: "Fee structures, invoicing, payment tracking, and financial reporting.",
    category: "finance_fees",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 2500,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["standard", "growth", "pro", "enterprise"],
    tags: ["fees", "invoices", "payments"],
    publishedAt: now,
  },
  {
    moduleId: "timetable",
    name: "Timetable & Scheduling",
    shortDescription: "Class scheduling with conflict detection for teachers, rooms, and subjects.",
    fullDescription: "Class scheduling with conflict detection for teachers, rooms, and subjects.",
    category: "academic_tools",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 1500,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["standard", "growth", "pro", "enterprise"],
    tags: ["timetable", "scheduling", "rooms"],
    publishedAt: now,
  },
  {
    moduleId: "hr",
    name: "HR & Payroll",
    shortDescription: "Staff records, leave, payroll, contracts, and performance workflows.",
    fullDescription: "Staff records, leave, payroll, contracts, and performance workflows.",
    category: "administration",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 3000,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["pro", "enterprise"],
    tags: ["staff", "payroll", "leave"],
    publishedAt: now,
  },
  {
    moduleId: "library",
    name: "Library Management",
    shortDescription: "Catalog books, manage circulation, and track overdue items and stock.",
    fullDescription: "Catalog books, manage circulation, and track overdue items and stock.",
    category: "academic_tools",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 1000,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["pro", "enterprise"],
    tags: ["books", "catalog", "circulation"],
    publishedAt: now,
  },
  {
    moduleId: "transport",
    name: "Transport Management",
    shortDescription: "Manage routes, fleets, drivers, and transport assignment operations.",
    fullDescription: "Manage routes, fleets, drivers, and transport assignment operations.",
    category: "administration",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 2000,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["pro", "enterprise"],
    tags: ["routes", "fleet", "drivers"],
    publishedAt: now,
  },
  {
    moduleId: "ewallet",
    name: "eWallet",
    shortDescription: "Cashless wallets, top-ups, balance tracking, and transaction history.",
    fullDescription: "Cashless wallets, top-ups, balance tracking, and transaction history.",
    category: "finance_fees",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 2500,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["enterprise"],
    tags: ["wallet", "cashless", "transactions"],
    publishedAt: now,
  },
  {
    moduleId: "ecommerce",
    name: "eCommerce",
    shortDescription: "Online store for uniforms, books, supplies, and school merchandise.",
    fullDescription: "Online store for uniforms, books, supplies, and school merchandise.",
    category: "finance_fees",
    publisherName: "EduMyles",
    pricingModel: "monthly",
    priceCents: 3000,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["enterprise"],
    tags: ["store", "orders", "products"],
    publishedAt: now,
  },
  {
    moduleId: "tickets",
    name: "Support Tickets",
    shortDescription: "Internal support desk for staff, students, and parents.",
    fullDescription: "Internal support desk for staff, students, and parents.",
    category: "communication",
    publisherName: "EduMyles",
    pricingModel: "free",
    priceCents: 0,
    currency: "USD",
    totalInstalls: 0,
    totalReviews: 0,
    averageRating: 0,
    isFeatured: false,
    isVerified: true,
    isSecurityReviewed: false,
    isGdprCompliant: false,
    compatiblePlans: ["free", "starter", "standard", "growth", "pro", "enterprise"],
    tags: ["support", "helpdesk", "sla"],
    publishedAt: now,
  },
];

export const FALLBACK_MARKETPLACE_CATEGORIES = [
  { slug: "academic_tools", name: "Academic Tools" },
  { slug: "communication", name: "Communication" },
  { slug: "finance_fees", name: "Finance & Fees" },
  { slug: "administration", name: "Administration" },
];
